### ISSUE TITLE
Tools & Resources top-level page

### ISSUE THREAD

**Issue by jamesatheyDDS** [deptofdefense/move.mil#108]
If you click on "Tools & Resources" in the side or top nav to go to the category page instead of one of the subcategories (like the Locator Maps), you get a "Coming Soon" page.

I'm not sure what we _need_ on this page, probably not much. At a minimum, it needs links to the subcategories. Do you have any thoughts, @lfantano?

**Comment by lfantano** [comment]
@jamesatheyDDS You're right, it will be a list primarily if links to the sub tools, with the addition of PDF copies of the regs and other more official documentation ... aka "resources".

**Comment by lfantano** [comment]
Ready for development: https://app.zeplin.io/project/596e69460294feaa7dcfb194/screen/59f0bd6fe09dd30099a8b053

Assets:
[tools&resources.zip](https://github.com/deptofdefense/move.mil/files/1415558/tools.resources.zip)

**Comment by aileendds** [comment]
This is live now :)
