### ISSUE TITLE
Move.mil Style Shifts and Navigation

### ISSUE THREAD

**Issue by lfantano** [deptofdefense/move.mil#120]
Site-wide style elements and changes. 

- [ ] Fix the "Back to Top" element onto the right side of the screen.

- [ ] Remove the side nav in favor of site-wide header navigation

**Comment by lfantano** [comment]
- [ ] Add USDS breadcrumb navigation below the header on subpages.
https://app.zeplin.io/project/596e69460294feaa7dcfb194/screen/59f0a77f973c21933746c4ae

**Comment by aileendds** [comment]
@lfantano for the "Back to Top" button, which parts are pinned? I thought it was just the button but in the designs (e.g. tools and resources page) it overlaps with the content. Is the entire header fixed and just the content scrolls?

**Comment by lfantano** [comment]
@aileendds I'm not sure I understand. 

The "Back to Top" button is pinned to the right side of the browser. Depending on browser width, this might overlap some content as the user scrolls, but since it is a narrow element, I'm ok with this. 
I don't think onload the "Back to Top" button will overlap content since it's positioned next to the titles, which are horizontally shorter. Let me know if that's not the case. 

For the Entire top navigation, it wasn't my intention that the navigation was fixed, although it could be. I'm more indifferent on that. If we end up fixing it though, I'd like to add the opacity back on the subpages, so the user can see the text scroll behind the header. 

Make sense? @aileendds
