### ISSUE TITLE
Moving with the Military: Update V2

### ISSUE THREAD

**Issue by jde1984** [deptofdefense/move.mil#123]
## Expected Behavior

On the "Moving with the Military" page of beta.move.mil, the TDY language needs to be adjusted.  Per the JTR, the shipment of HHG's/UB while on a TDY must exceed 31 days.  Recommend we add in the "must exceed 31 days" in the overview part before going in depth. 

"A Service member who is on TDY for 31 or more days may be eligible for travel allowances to ship HHG." JTR / CH2 / Section 0205

## Observed Behavior

Temporary Duty Yonder (TDY) is when you are temporarily assigned to a new location, for generally less than 20 weeks. For TDY, it is common that only a small subset of your household belonging will be able to travel with you to your new location. What to expect for a TDY move?

## Steps to Reproduce

Go here: http://beta.move.mil/moving-guide
Look. 

## Screenshots

N/A

**Comment by lfantano** [comment]
The designs for "Moving with the Military" have been added to Zeplin:
https://app.zeplin.io/project/596e69460294feaa7dcfb194/screen/596e69b24811bfcca660fb35

No knew graphics needed:

The chart switches to the accordion/drop down format with screen-width <500px. 

Thanks!

**Comment by aileendds** [comment]
Where does the "Military Claims Office" link under the HHG move type go?

**Comment by lfantano** [comment]
It should go to the Customer Service page, anchored down to the Claims
section.
