### ISSUE TITLE
Add code.mil tag?

### ISSUE THREAD

**Issue by jordangov** [deptofdefense/move.mil#126]
Hello! I would like to add the `code-mil` tag to this repository. It will identify the repo as being an open source DoD project ([searchable using the tag](https://github.com/topics/code-mil)). If you have any questions let me know!

(FYI, I can add the tag if you wish, just need a :+1:)

**Comment by Elliottdotgov** [comment]
@jordangov go ahead and add the tag and put it in a PR!

**Comment by jordangov** [comment]
Hmm... don't think I can put it in a PR as it isn't really code... just a tag on the repo in GH. I'll go ahead and add it (when you go to the project main page you can see it under the name of the repo). Let me know if there's any issues!
