### ISSUE TITLE
What to Expect... Claims

### ISSUE THREAD

**Issue by jde1984** [deptofdefense/move.mil#135]
Needs:

- [x] Page Template/Design
- [x] Content
- [ ] Implementation

**Comment by jde1984** [comment]
https://docs.google.com/a/dds.mil/document/d/1RJAro2HzR2uY4xl2ynqCGH95grzPaEXm4yJznNsat9Q/edit?usp=sharing

**Comment by lfantano** [comment]
Designs are on Zeplin: https://zpl.io/b6JZ5oK
No graphics needed....

The page should be added to the Moving Guide below Reimbursements, above Moving Tips.

**Comment by aileendds** [comment]
@lfantano @LillyMadigan Where does the Military Claims Office link go?

**Comment by lfantano** [comment]
To the anchored to the claims section on the Customer Service Page!
@aileendds

**Comment by aileendds** [comment]
Does "local" in the "local Military Claims Office" links make sense? Looking at the customer service page, it looks like there is one office per service, which is not necessarily local to the service member.

**Comment by lfantano** [comment]
Fair point- let's remove the word "local"

**Comment by aileendds** [comment]
Where should the DD1840 form link go? We don't have this form in Tools & Resources.

**Comment by jde1984** [comment]
DD1840 does not have a link and no one from AT&L will confirm it's existence anymore.  You can find half-baked ones online, but I'm not sure if they are accurate.  Ideally, it would link off the DoD Forms site (http://www.esd.whs.mil/Directives/forms/dd1500_1999/) but if you go down to 1840 there's no link.

**Comment by jdsager** [comment]
The DD Form 1840 does not exist any more... any reference to the 1840 needs to be changed to just the "Notification of Loss or Damage At Delivery Form"
