### ISSUE TITLE
What to Expect ... CONUS

### ISSUE THREAD

**Issue by lfantano** [deptofdefense/move.mil#142]
Designs are uploaded to Zeplin
https://app.zeplin.io/project/596e69460294feaa7dcfb194/screen/59fcad1b1ed6d9015cc40f57

No new graphics necessary.

**Comment by lfantano** [comment]
1. "family support center" could go to http://www.militaryinstallations.dod.mil/MOS/f?p=MI:ENTRY:0
2. Yep!
3. Let's update the text to: This will ensure that nothing gets left behind and if you see any damage to the residence you can annotate that on a or DD Form 1840, which your driver should have on hand...

Let's also have "DD Form 1840" link to the Tools & Resources Page, to a "Forms" section below the DOD Lodging section. @jde1984 is tracking down the actual form.

**Comment by aileendds** [comment]
This is done except #3 linking to the Tools & Resources page with a "Forms" section, since we don't have that section yet. @jde1984 do you think we'll have that in time for launch or should we table this?

**Comment by jde1984** [comment]
@aileendds - forms:
https://docs.google.com/a/dds.mil/document/d/1snMDdK9OsZq6eKC5mAeZBJ6B82O-4MuW_sq_cx0JaII/edit?usp=sharing

**Comment by aileendds** [comment]
@jde1984 what about the DD Form 1840?

**Comment by jde1984** [comment]
DD 1840 doesn't exist anymore... OSD AT&L doesn't have it anymore on their site.  You can find older copies, but I tried to link each form back to the source so if they made any changes.  Majority of TSPs use a Notification of Loss or Damage Form - there's no number as it's locally developed.  

I notified USTC ... their response "SIDE NOTE:  This form should still be active, so not sure why you see it as no longer being maintained by AT&L.  We will have to look into that. "

**Comment by lfantano** [comment]
lol... Transcom.

**Comment by aileendds** [comment]
@jde1984 so should I change that sentence in CONUS to "This will ensure that nothing gets left behind and if you see any damage to the residence you can annotate that on a Notification of Loss or Damage Form, which your driver should have on hand."? And this won't link to the forms since we don't have that

**Comment by aileendds** [comment]
@lfantano, how is this?

![screencapture-localhost-3000-resources-1511805678934](https://user-images.githubusercontent.com/29409348/33281405-2c429b84-d373-11e7-8866-fe3f587942c9.png)

There's a lot of text which is different from the other sections. I could remove the text.

**Comment by jde1984** [comment]
@aileendds - I don't know if this form is geared toward damage to a residence... I think @lfantano found out that any damage to a residence goes through the MCO and would not go on this form so we may just need to remove that part.

**Comment by aileendds** [comment]
Ok, removing that part. Now it just says "After everything is loaded up on the truck, do a walkthrough with the driver to make sure everything is out of your residence and loaded up. This will ensure that nothing gets left behind. If possible, ask the driver for their phone number....."

**Comment by lfantano** [comment]
That looks great - thanks guys.

**Comment by jgarber623-gov** [comment]
Closed by #168.
