### ISSUE TITLE
Nightmare Moves Design Update

### ISSUE THREAD

**Issue by lfantano** [deptofdefense/move.mil#145]
Nightmare Moves designs can be found at Zeplin:
https://app.zeplin.io/project/596e69460294feaa7dcfb194/screen/5a04e0a104bfb043c0ccf647

Graphics:
[NightmareMoves.zip](https://github.com/deptofdefense/move.mil/files/1465139/NightmareMoves.zip)

**Comment by aileendds** [comment]
- do we know the form in the Drywall Debacle (love these names btw) pro-tip? "Fill out Form ____ and the TSP can be financially responsible for fixing any damage caused by the moving crew."
- where does the codes link at the bottom of the soiled sofa pro-tip go?

**Comment by lfantano** [comment]
Oh! The Form doesn't exist. Justin was trying to track it down... The last
sentence should be "Report any damage to your moving company, they are
responsible for fixing any residential damage they cause during the move.
If you have problems, you can contact the Quality Assurance Inspector at
your local personal property office for help." local personal property
office will link to the PPPO map like everywhere else on the site.

For the codes: Here is the link:
https://www.ustranscom.mil/cmd/associated/dteb/files/refdata/V_D_PPLB_HHGDI_EX_CD.htm
