### ISSUE TITLE
Footer rendering problems on IE11

### ISSUE THREAD

**Issue by jamesatheyDDS** [deptofdefense/move.mil#149]
## Expected Behavior

Expect the page to render similarly without obvious problems on all supported browsers, including IE11.

## Observed Behavior

On IE11, the TRANSCOM logo in the footer of each page is extremely vertically stretched and distorted.

## Steps to Reproduce

To reproduce this issue…

1. Go to any page on http://beta.move.mil, including the home page, on a Windows machine running IE11. ([Free IE11 VMs are available from Microsoft.](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/))
1. Scroll to the bottom of the page.

## Screenshots

![ie11-render-fail](https://user-images.githubusercontent.com/26554826/32790870-944e6118-c92d-11e7-95f8-7180ae77a24b.png)

**Comment by jgarber623-gov** [comment]
Closed by #169.
