### ISSUE TITLE
Browser Compatibility Check

### ISSUE THREAD

**Issue by Elliottdotgov** [deptofdefense/move.mil#158]
Before launch we should do a review of site on various versions of IE, Edge and other browsers commonly in use.

**Comment by aileendds** [comment]
IE10 - entitlements special item information icon links are all in 1 column

**Comment by Elliottdotgov** [comment]
Probably worth another review of browsers once we push Service Specific info, Entitlements, and PPM Estimator

**Comment by aileendds** [comment]
Sometimes after the initial load / refreshing the page, the top nav dropdown buttons (Moving Guide, Tools & Resources) dont expand the dropdown.

**Comment by aileendds** [comment]
IE10 - Some pages are more narrow than others (e.g. locator maps is more narrow than homepage)

**Comment by jamesatheyDDS** [comment]
I'm closing this - launch has happened, and we should file individual issues for problems we see in particular browsers.
