### ISSUE TITLE
Design and Build error pages

### ISSUE THREAD

**Issue by jgarber623-gov** [deptofdefense/move.mil#161]
We could use a lightweight 404 page! [The current page](http://beta.move.mil/404) is the Rails default and isn't very attractive.

**Comment by lfantano** [comment]
Designs have been uploaded onto Zeplin.
https://zpl.io/adRrWyR

Assets attached. 
[404.zip](https://github.com/deptofdefense/move.mil/files/1492690/404.zip)

**Comment by jde1984** [comment]
@jgarber623-gov @lfantano ... for the 404 page, we spelled "address" wrong. 

What it currently says... "It looks like the page you’re looking for can’t be found.  You may have mistyped the adress or the page may have moved."

**Comment by jgarber623-gov** [comment]
Fixed as of 0abb8f7.
