### ISSUE TITLE
Tutorial: Create a Shipment 

### ISSUE THREAD

**Issue by LillyMadigan** [deptofdefense/move.mil#173]
Updated content by page can be found in this google doc https://docs.google.com/a/dds.mil/document/d/1GWxy71J9fS8Cn6To834N4M2IsP57V_ZcKdGKTI55GSI/edit?usp=sharing

design is up in Zeplin
images are in progress

**Comment by jgarber623-gov** [comment]
Superseded by #182.

**Comment by LillyMadigan** [comment]
Content: https://docs.google.com/a/dds.mil/document/d/1GWxy71J9fS8Cn6To834N4M2IsP57V_ZcKdGKTI55GSI/edit?usp=sharing

Images: https://drive.google.com/open?id=19259V-d5xRG-K9CJNqpoH-hIV1LQ52ay

**Comment by LillyMadigan** [comment]
Design is up in Zeplin

**Comment by aileendds** [comment]
@LillyMadigan where does the "Consignment Instruction Guide" link go?

**Comment by LillyMadigan** [comment]
@aileendds sorry about that! https://tops.ppcigweb.sddc.army.mil/ppcig/menu/query/country.do

**Comment by aileendds** [comment]
@LillyMadigan - hmm actually that link doesn't work for me

**Comment by aileendds** [comment]
I ended up deleting the sentence with the consignment instruction guide. @LillyMadigan I just noticed though that you updated it to say "Contact your gaining Transportation Office (the one you’re moving to) for their motorcycle shipping information." Should I just go ahead and add this everywhere it's used, or is @jde1984 still trying to track down the instruction guide?

**Comment by LillyMadigan** [comment]
Until such a time that we can be more helpful, let's leave it with the cautionary statement that is in prod (slide 14 of Create a Shipment). @aileendds

**Comment by aileendds** [comment]
Ok sounds good! I'll close this issue then.
