### ISSUE TITLE
Customer Service Update

### ISSUE THREAD

**Issue by lfantano** [deptofdefense/move.mil#174]
We need to update the customer service page to follow the format of the other article-based pages. Basically this means, the content will become slightly narrower and there will be the anchored navigation in the following categories to the left:

- Local Personal Property Office
- Service Branch Customer Service (THIS IS A SLIGHT CHANGE IN THE TITLE)
- Technical Help Desk
- Accounting & Finance Office
- Claims
- Retiree/Separatee Extentions

Also: 

- [ ] Can we add the following URL [www.jag.navy.mil/organization/code_15.htm](url) to the Navy claims info - it is their claims website.

- [ ] For Retiree/Separtee Extentions for Army, there should be a note that "Requests for retirement extensions should be submitted through your local personal property office (PPPO)." With the Locator map link over "Local Personal Property Office (PPPO)"

Thanks! Sorry there's not a mock, let me know if there are questions.

**Comment by aileendds** [comment]
@lfantano can you take a look at the screenshots here to see if this is what you described?

https://github.com/deptofdefense/move.mil/pull/176
