### ISSUE TITLE
Content: What to Expect Civilian

### ISSUE THREAD

**Issue by LillyMadigan** [deptofdefense/move.mil#179]
What to expect DoD Civilian move (desktop + mobile) content and design is up In Zeplin

@Elliottdotgov could you give it a grammatical once over? thanks!!

**Comment by Elliottdotgov** [comment]
Looks good but there's a slight issue with sizing in one place; the space doesn't show the full text  - > see image

<img width="547" alt="screen shot 2017-11-30 at 9 03 34 am" src="https://user-images.githubusercontent.com/25456509/33437428-80dc4906-d5ad-11e7-8bd5-9dd545cdd381.png">

**Comment by Elliottdotgov** [comment]
(look at the very end, the sentence with the parenthesis is cut off)

**Comment by aileendds** [comment]
@LillyMadigan: Is this really 0.17 cents / mile or is it 17 cents / mile?
"Currently, the mileage rate for POV reimbursement is .17 cents per mile"

**Comment by aileendds** [comment]
Where do these links go? 
- per diem
- The Relocation Income Tax Allowance (RITA)
- Miscellaneous Expense Allowance (MEA)

**Comment by LillyMadigan** [comment]
@aileendds nope, it should read $0.17/mile, good catch thank you. 

Per Diem https://www.defensetravel.dod.mil/site/perdiemCalc.cfm

RITA https://www.dfas.mil/civilianemployees/civrelo/relocationincometax.html

MEA https://www.dfas.mil/civilianemployees/civrelo/miscexpenseallowance.html

**Comment by LillyMadigan** [comment]
@aileendds @jde1984 yup - last bullet point is missing the last word "away)"

"A sheet of paper with your new base address, shuttles, rental car information (since you may not have cell service right away)"
