### ISSUE TITLE
Tutorials 

### ISSUE THREAD

**Issue by LillyMadigan** [deptofdefense/move.mil#182]
New design for tutorials page (desktop and mobile) 'coming soon' for launch, up in Zeplin.

**Comment by jamesatheyDDS** [comment]
@LillyMadigan In Zeplin, the design has the side nav with the names of the tutorials we've made thus far, but with only the coming soon text. Are the tutorials we've built so far getting removed? Or is the banner there more of an "under construction" sign that we're putting in front of the content we've already completed?

**Comment by lfantano** [comment]
@jamesatheyDDS Yes! The tutorials were inaccurate which is why this new coming soon page is important!

**Comment by lfantano** [comment]
The side nave is placeholder essentially which will eventually anchor down the page once there is content.

**Comment by LillyMadigan** [comment]
Content for "Login To DPS" https://docs.google.com/a/dds.mil/document/d/12tXba4z2sYAuxOwn7sQcKBBnyg8SFV8oprE6V7Lx4XM/edit?usp=sharing

Images for "Login To DPS" https://drive.google.com/open?id=1tXd9NjO7sxLRJ2lCSvBbQLA81AWySXrG

**Comment by LillyMadigan** [comment]
All Tutorial work is now in it's own issue
