### ISSUE TITLE
Entitlements Spruce Up....

### ISSUE THREAD

**Issue by lfantano** [deptofdefense/move.mil#183]
- [x] Update the Entitlement template to the newer article style with the side anchors. The sections are: What am I allowed to bring?, Your Moving Allowance, and Special Item Information

- [x] In the current "What am I allowed to bring section?" shift the "Enter your rank, dependency status,..." instructions along with the form inputs down into the "Your Moving Allowance" section below the "Moving allowances are generally based..." text, but above the information needed callout. 

- [x] At the bottom of the moving allowance section we need a disclaimer (stay tuned will post image momentarily.

- [x] In the "Special Items" section, we need a disclaimer added below the blue category anchors but above the table.  (disclaimer below)

- [x] In the "Special Items" section change the Green H3 text to Source Sans Pro semibold, #000000 (we moved away from the green text on all the other pages...

**Comment by lfantano** [comment]
[alert_important.svg.zip](https://github.com/deptofdefense/move.mil/files/1518046/alert_important.svg.zip)
Here are the disclaimers.
<img width="907" alt="screen shot 2017-11-30 at 8 08 42 am" src="https://user-images.githubusercontent.com/22291512/33434732-bee50934-d5a5-11e7-88f0-12f9c684dddb.png">

**Comment by lfantano** [comment]
Ok that "Your Moving Allowance" makes no sense, lets do:
"Certain overseas (OCONUS) locations have weight restrictions due to limited housing and storage availability. If you are moving to an overseas (OCONUS) location with restrictions any excess weight above your restricted weight up to your full weight entitlement can be placed in stateside longterm "non-temporary" storage (NTS)."

Also in "Special Items" "local personal property office needs the link...

**Comment by lfantano** [comment]
- [ ]  Include "civilian employee" in the "Select your military pay grade" dropdown.

Civilians get 18,000 pound allowance  to the "what am I allowed to bring?" form (They also get the same pro gear as the uniformed folks)

**Comment by lfantano** [comment]
- [ ] The "What am I allowed to bring?" section text should be replaced with the following:

Moving allowances, also known as entitlements, are largely based on the service member or civilians rank and dependency status. However, special circumstances like moving overseas (OCONUS), a retirement move, or a separation move may have extra entitlements and/or limitations than the standard Permanent Change of Station (PCS) move within the continental United States.

The information below is designed to help you understand these allowances and provide information that will help you through the moving process.  While considerable effort was taken to ensure this information is accurate, ultimately, the Joint Travel Regulation (JTR) is the authority of entitlements for all service members and each branch of the services has supplemental regulations or guidance in addition to the JTR.  If you run into a situation where you need clarification of any of these points, or just want to make sure you understand the official rules, you should reach out to your [local Personal Property Office (PPPO)](url: to Locator Map) for advice and guidance.

**Comment by lfantano** [comment]
- [ ] In the "Pets & Live Animals" section: "For OCONUS:... " text should be changed to "For OCONUS: Some host countries/international bases may limit the animal species and dog breeds allowed and may have specific quarantine requirements for some animals. In some cases, quarantine fees may be [reimbursable](link to Reimbursements page). Make sure you contact your new duty station before making plans to travel with your pets.

- [ ] In the "Firearms" section,  the OCONUS sentence should be changed to "You can transport firearms as part of your total household goods shipment, assuming that it abides by all the laws of your host country and your new country. When returning to the United States, you must identify firearms on your individual customs forms and obtain an ATF Form 6. You can access the ATF Form 6 for military personnel [here](LINK: Helpful Links- Forms Section. ) and civilians [here](LINK: Helpful Links- Forms Section. ). Allow up to 6 weeks for processing. It is recommended you contact your [local personal property office](LINK: to Locator Map) for assistance."

- [ ] In the "Firearms" section, consolidate the first two bullet points to say, "You can transport firearms as part of your total household goods shipment, assuming that it complies with all local and state laws. If you intend to self-transport firearms in your vehicle, make sure you do not carry your weapon on your person and check all the laws of every state you intend to drive through to your new duty station."

**Comment by lfantano** [comment]
- [ ] For the "Alcohol" section, delete the first bullet.

**Comment by aileendds** [comment]
@lfantano - do you have the asset for the yellow warning symbol? Alternatively I can use the "Warning Status" alert style here: https://standards.usa.gov/components/alerts/

**Comment by lfantano** [comment]
The assets is the zip file in the issue. GitHub blocks SVGs as a file type
for some reason so I have to zip it

**Comment by aileendds** [comment]
Oh my bad totally missed that link.

**Comment by jamesatheyDDS** [comment]
@lfantano @aileendds Why not just use the US WDS alerts in this case? We use those alerts in other places already.

**Comment by aileendds** [comment]
I implemented it with the USWDS alert and it seems fine other than when the results are focused:
 <img width="869" alt="screen shot 2017-12-01 at 3 15 25 pm" src="https://user-images.githubusercontent.com/29409348/33502562-97072adc-d6ae-11e7-9534-b7d1f04541a5.png">

Maybe for this we can change the focus background color?

**Comment by lfantano** [comment]
That works for me

**Comment by aileendds** [comment]
@lfantano any preference?
1. No bg color:
<img width="858" alt="screen shot 2017-12-01 at 3 56 06 pm" src="https://user-images.githubusercontent.com/29409348/33502993-3456afbe-d6b0-11e7-9730-173270b53ebf.png">

2. cool-gray-light
<img width="827" alt="screen shot 2017-12-01 at 3 55 03 pm" src="https://user-images.githubusercontent.com/29409348/33503003-3bb49686-d6b0-11e7-82e1-91cb721e85c7.png">

3. warm-gray-light
<img width="814" alt="screen shot 2017-12-01 at 3 54 09 pm" src="https://user-images.githubusercontent.com/29409348/33503022-4485ac46-d6b0-11e7-9df2-5c8634a21ac0.png">

**Comment by aileendds** [comment]
Went with the no background color option!

**Comment by lfantano** [comment]
Great choice!!
