### ISSUE TITLE
Locator Map Wrapping issue

### ISSUE THREAD

**Issue by Elliottdotgov** [deptofdefense/move.mil#185]
<img width="1330" alt="screen shot 2017-11-30 at 7 58 33 am" src="https://user-images.githubusercontent.com/25456509/33434329-a12d0884-d5a4-11e7-8f02-0e8a865f2897.png">

**Comment by jgarber623-gov** [comment]
☝️  This isn't a _real_ fix, but it resolves the immediate issue in most cases.
