### ISSUE TITLE
Locator Map example zip check (20050)

### ISSUE THREAD

**Issue by Elliottdotgov** [deptofdefense/move.mil#186]
Error for the example zip (20050)

<img width="1231" alt="screen shot 2017-11-30 at 8 03 02 am" src="https://user-images.githubusercontent.com/25456509/33434515-22daa8e6-d5a5-11e7-8ac8-1d6e2dc4f370.png">

**Comment by Elliottdotgov** [comment]
unless this is a quick fix let's move this to the 'after launch' queue

**Comment by jgarber623-gov** [comment]
20050 is not a valid ZIP code according to the data we have, which is why the page is showing an error.
