### ISSUE TITLE
Customer Service: Army Claims

### ISSUE THREAD

**Issue by lfantano** [deptofdefense/move.mil#188]
Under Army claims can you add a link below the contact info. "For claims related moves to overseas (OCONUS) locations, international claims contacts can be found [here](url: Link to the Army service specific page).

**Comment by jamesatheyDDS** [comment]
@lfantano The army service specific page doesn't have any content related to OCONUS claims, right? It just talks about the Center for Personnel Claims Support which handles CONUS claims + Hawaii and Puerto Rico.

**Comment by lfantano** [comment]
No it does- it's in the update @aileendds is doing now.

**Comment by jamesatheyDDS** [comment]
This issue needs to wait until the service specific content is restored.
