### ISSUE TITLE
Update Tools & Resources: Forms section to include Firearms forms.

### ISSUE THREAD

**Issue by lfantano** [deptofdefense/move.mil#197]
There are two ATF Form 6 forms that need uploaded - one for service members and one for civilians.

Here is the service member one:
 [](https://www.atf.gov/firearms/docs/form/form-6-part-2-application-and-permit-importation-firearms-ammunition-and) the text should say: "**ATF Form 6 (Active Duty Service Members Only):** This form is used by Active Duty Military members to apply to permanently import firearms, ammunition and implements of war into the United States.

Here is the civilian one:
 [](https://www.atf.gov/firearms/docs/form/form-6-part-1-application-and-permit-importation-firearms-ammunition-and) the text should say: "**ATF Form 6 (Active Duty Service Members Only):** This form is used by civilians apply to permanently import firearms, ammunition and implements of war into the United States.

**Comment by lfantano** [comment]
URLS:
Civilian: https://www.atf.gov/firearms/docs/form/form-6-part-1-application-and-permit-importation-firearms-ammunition-and

Military
https://www.atf.gov/firearms/docs/form/form-6-part-2-application-and-permit-importation-firearms-ammunition-and

**Comment by jgarber623-gov** [comment]
@lfantano Should the link for the civilian form read, "ATF Form 6 (Active Duty Service Members Only)" as in this issue's description?

**Comment by lfantano** [comment]
@jgarber623-gov The civilian one should read:

"**ATF Form 6 (Civilians & Non-Active Duty Service Members):** This form is used by civilians and non-active duty service members apply to permanently import firearms, ammunition and implements of war into the United States.
