### ISSUE TITLE
Quick Content Change: FAQ

### ISSUE THREAD

**Issue by lfantano** [deptofdefense/move.mil#198]
The FAQ - "what happens if there is an accident during my PPM Move" needs to be modified to "If you get into an accident during your move, the government provides up to $50,000 of insurance on your lost property if you are found not at fault. (It is suggested that you file a claim even if you are unsure about fault or other determinations as well.) it is The insurance doesn’t cover any damage to the vehicle - only to your household goods."

**Comment by jgarber623-gov** [comment]
@lfantano There's a grammatical error between "other determinations as well.) it is The insurance"…

Can you confirm the correct content?

**Comment by lfantano** [comment]
Let's try:
