### ISSUE TITLE
Update to USWDS 1.4.x?

### ISSUE THREAD

**Issue by jamesatheyDDS** [deptofdefense/move.mil#213]
There are several visual changes in the latest USWDS that apply to us and we may be interested in.

https://standards.usa.gov/whats-new/releases/#version-140

There are changes to how alerts, buttons, select boxes, and menus look.

**Comment by aileendds** [comment]
Let's do it. I just tried switching it to 1.4.3 and everything seems ok for the most part although I haven't looked in depth yet. Although I remember @jgarber623-gov previously mentioned it caued some issues?
