### ISSUE TITLE
Content (V2): Updated FAQ's

### ISSUE THREAD

**Issue by jde1984** [deptofdefense/move.mil#215]
Add any additional FAQ's... 

Current FAQ's:
http://www.move.mil/faqs

V2 List:
https://docs.google.com/a/dds.mil/document/d/1TiRNA76qCCb5vteBjncdWFO8lTtz18BLGrmeCXW7v68/edit?usp=sharing

**Comment by aileendds** [comment]
I added these to the site; if there are more new FAQs to add let's open a new issue
