### ISSUE TITLE
typo: Navy Customer Service url

### ISSUE THREAD

**Issue by Elliottdotgov** [deptofdefense/move.mil#218]
current (incorrect) url: https://www.navysup.navy.mil/household
correct url: https://www.navsup.navy.mil/household

worth doing a global Find and Replace for this url but I found it on this page: https://www.move.mil/customer-service#svc-help

![screen shot 2017-12-05 at 2 46 03 pm](https://user-images.githubusercontent.com/25456509/33627301-1b1a703a-d9cb-11e7-91c8-ff6859f1ba76.png)

**Comment by aileendds** [comment]
I think that's the only spot: https://github.com/deptofdefense/move.mil/search?utf8=%E2%9C%93&q=navysup&type=
