### ISSUE TITLE
[IE11] "Here's how you know" appearing on second line in the banner on IE11

### ISSUE THREAD

**Issue by jamesatheyDDS** [deptofdefense/move.mil#241]
Not sure when it started, perhaps with the USWDS upgrade, but the link "Here's how you know" in the banner is now flowing to a second line on IE11.

Ignore the "Content" text in the top of this screenshot; that's an artifact from netrenderer.com. 

![heres_how_you_know_ie11](https://user-images.githubusercontent.com/26554826/33889696-ef0f8cc4-df1e-11e7-9ddf-df28d2d72781.png)

**Comment by aileendds** [comment]
This has always been there, I commented on the USWDS issue 2 weeks ago but no movement there :T: https://github.com/18F/web-design-standards/issues/1984

**Comment by jgarber623-gov** [comment]
Adding `blocked` tag while waiting on an upstream fix in USWDS.

**Comment by jgarber623-gov** [comment]
Resolved upstream by USWDS 1.4.6 and here by 931045b. 🎉
