### ISSUE TITLE
[IE10] Top nav dropdown buttons don't expand when clicked

### ISSUE THREAD

**Issue by aileendds** [deptofdefense/move.mil#243]
It's not consistently reproducible but often happens after the initial page load or refreshing the page.

**Comment by jgarber623-gov** [comment]
This one is really strange. I can reproduce it IE10 when…

1. Clear the cache by opening F12 Developer Tools and pressing `ctrl-r`,
2. Navigate to https://www.move.mil,
3. Observe that dropdown navigation of any sort (including the "Here's how you know" banner at the top) doesn't function properly,
4. Navigate to another page (e.g. `/tutorials`),
5. Observe that the navigation works.

The initial page in Step 2 doesn't matter. Dropdown navigation only works after navigating from the first page to another page. 🤔

**Comment by jamesatheyDDS** [comment]
We don't care about IE10. The only version of IE we care about is IE11.
