### ISSUE TITLE
Simple static 404 page

### ISSUE THREAD

**Issue by aileendds** [deptofdefense/move.mil#262]
Because Rails doesn't have a fantastic way of showing dynamic 404 pages, it would be simpler and more reliable if we had a very basic and static (html + light css + few assets) version of the 404 page. This wouldn't use the existing page layout with the header, and be closer to something like this with just a link to the homepage: http://google.com/asdf

It would also be nice to have a very similar basic 500 (generic error page). Some examples: https://rigor.com/blog/2012/07/15-awesome-fail-pages

**Comment by LillyMadigan** [comment]
@aileendds I'm on it! do you have a copy of the sketch file?

**Comment by jgarber623-gov** [comment]
Closing this one as it appears to be resolved by #268.
