### ISSUE TITLE
Spelling corrections: What to expect CONUS move

### ISSUE THREAD

**Issue by LillyMadigan** [deptofdefense/move.mil#269]
on this page, please replace the following content:

1.) OLD: "For starters, they can do a full unpack, which is basically where hey empty all the items of the boxes in the specified rooms. "

NEW: hey should be they.

2.) OLD: "It's critical that you are available during this time and for some reason if they fail to show during the window that you, notify your local personal property office (PPPO) quickly."

NEW: remove the ',' after the you.

**Comment by aileendds** [comment]
For #2, should this be add "specified" after you rather than remove the comma?

**Comment by LillyMadigan** [comment]
No, they set the window time, not the service member. I clarified (hopefully), by splitting up the sentences. below is the new text. 

"It's critical that you're available during this time. If for some reason the Moving Company fails to show, quickly notify your local personal property office (PPPO)."

**Comment by aileendds** [comment]
Ohh I get it now. Yup it's clearer, will update!

**Comment by aileendds** [comment]
@LillyMadigan - I also see in civilians and oconus the sentence was changed to this: 

"It's critical that you are available during this time and if for some reason they fail to show during the window, notify your local personal property office quickly." 

Would you like me to change this also to match the new language or vice versa?

**Comment by aileendds** [comment]
Updated all to the text in comment above ^
