### ISSUE TITLE
Spelling/Admin Issue(s)

### ISSUE THREAD

**Issue by jde1984** [deptofdefense/move.mil#276]
* Not sure if we want to keep this open for to see if we catch anything after the Ft Bragg trip, but if not, just some minor admin/spelling items. 

#1 
Go here:
https://www.move.mil/moving-guide
Third Paragraph States "Permanent Duty Station (PCS) is when you are assigned to a location for 20+ weeks, regardless of whether your assignment pertains to training or a new job. In these circumstances, you should be allowed a full household move should you choose to take it."

The acronym is "Permanent Change of Station (PCS)..."

#2
https://www.move.mil/moving-guide/tips
The number rule tip professional organizers like to give is: if you haven’t used an item in two years, you don’t need it anymore.

**Comment by jgarber623-gov** [comment]
Resolved by #277.
