### ISSUE TITLE
Fix JPPSO PH Contact Info

### ISSUE THREAD

**Issue by lfantano** [deptofdefense/move.mil#278]
Change the primary phone number for JPPSO Pearl Harbor, HI from (808) 473-7747 to  **808-473-7750**

**Comment by lfantano** [comment]
Can you let me know when this pushes to production? I'd like to let them
know!

**Comment by lfantano** [comment]
"Could you also please change the DSN number as well . . currently reads 315-473-7747 (voice) (DSN) and the last 4 should be 7750 as well.  Sorry for the hassle."

**Comment by jgarber623-gov** [comment]
Resolved by 9d9328e0.
