### ISSUE TITLE
https://www.move.mil/tutorials/schedule-a-move hitting a server error.

### ISSUE THREAD

**Issue by ntwyman** [deptofdefense/move.mil#281]
Searched google for DD1299 and the above link came up in the google results. Following the link, I hit a womething went wrong page.

Thanks for submitting an issue! Below are a few things you can do to help us more quickly address the issue.

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [x] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [ ] attached screenshots illustrating relevant behavior.

## Expected Behavior
Link on the site should either resolve to a page or show a Page not Found error.

## Observed Behavior
Loading that URL causes an server error. Reproduced with Chrome and Safari on up to date Mac Laptop

## Steps to Reproduce

To reproduce this issue…

1. Open a browser session and enter 'https://www.move.mil/tutorials/schedule-a-move'
1. Observe error
<img width="1343" alt="screen shot 2018-01-08 at 12 45 11 pm" src="https://user-images.githubusercontent.com/317739/34691710-53b9a016-f472-11e7-81f7-2a01c594605d.png">

1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._

**Comment by aileendds** [comment]
This was from an old tutorials link that we no longer have. Theoretically it should drop out of Google search results soon. However, we shouldn't be showing 500s for these. We can either 404 or redirect to /tutorials.
