### ISSUE TITLE
Missing weight scales ft bragg

### ISSUE THREAD

**Issue by hatueyustc** [deptofdefense/move.mil#283]
Adding jpg (or attempting to)
![151561666484426652198](https://user-images.githubusercontent.com/35311339/34794327-4ec0eb9a-f61c-11e7-89ec-8d493fcc4843.jpg)

**Comment by Elliottdotgov** [comment]
Thanks @hatueyustc! Can you add some context here (written description)? 

Also, can you type out the locations as a comment here so we can paste in quickly? 

Thanks!

**Comment by hatueyustc** [comment]
Context: These should be added to the scale locator results for ft bragg on the new move.mil

Typing: recommend scanning into pdf with ocr text recognition so no one has to retype (no access to keyboard currently)

**Comment by schustdj** [comment]
Are there any ideas out there on how to ingest the weight scales information for all locations? One idea I have is the creation of a web form that the PPPOs can use to submit info, that someone can review before adding the locations...

**Comment by hatueyustc** [comment]
The previous owner of the archive.move.mil html code (USAF JPPSO NE Deputy R DePietro) used to maintain scale info and PPPO phone numbers using a method that sounded like web forms and reports it was way more accurate than archive.move.mil has been
