### ISSUE TITLE
Loss and Damaged Claims Section - Change first sentence under "Lost & Damaged Household Goods Section 

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#287]
Thanks for submitting an issue! Below are a few things you can do to help us more quickly address the issue.

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior

_Summarize expected behavior._
Change first sentence under "Lost & Damaged Household Goods Section to read "If any of your household goods are lost or destroyed during the moving process, you are entitled to full replacement value of that item, assuming your claim is filed within the nine months following the date of delivery. "
## Observed Behavior

_Summarize observed behavior._
If any of your household goods are lost or damaged during the moving process, you are entitled to the full replacement value of that item, assuming your claim is filed in a timely manner.

## Steps to Reproduce

To reproduce this issue…

1. _Describe step one._
1. _Describe step two._
1. _etc. etc. etc._

_Attach relevant screenshots here._ Would not let me load screen snipped

**Comment by jdsager** [comment]
Change first sentence under "Lost & Damaged Household Goods Section to read "If any of your household goods are lost or destroyed during the moving process, you are entitled to full replacement value of that item, assuming your claim is filed within the nine months following the date of delivery. "

**Comment by hatueyustc** [comment]
![loss damage screen](https://user-images.githubusercontent.com/35311339/35010914-0ab7702e-faca-11e7-8743-b3110d5719e8.JPG)

**Comment by hatueyustc** [comment]
![loss damage screen](https://user-images.githubusercontent.com/35311339/35011021-67e4cb0c-faca-11e7-9bf0-f4e874cd6f39.JPG)

**Comment by hatueyustc** [comment]
![loss damage screen](https://user-images.githubusercontent.com/35311339/35011045-7e79573e-faca-11e7-9290-403d9ac46c70.JPG)

**Comment by hatueyustc** [comment]
[https://www.move.mil/moving-guide/claims](url)

**Comment by hatueyustc** [comment]
![image](https://user-images.githubusercontent.com/35311339/35011257-1dc8cb1c-facb-11e7-8c9a-9aea614c336e.png)

**Comment by hatueyustc** [comment]
Might be an issue with Microsoft Edge but can't seem to paste images (jpgs or pngs)

**Comment by hatueyustc** [comment]
![loss damage screen](https://user-images.githubusercontent.com/35311339/35011319-91104b36-fafd-11e7-8ddc-fb850683b21c.JPG)

**Comment by ERESOS73** [comment]
![claims screen for 287](https://user-images.githubusercontent.com/35410335/35012611-3ca5a58c-fb02-11e7-9f21-971b2fdeec87.PNG)

**Comment by ERESOS73** [comment]
[claims screen for 287.pdf](https://github.com/deptofdefense/move.mil/files/1636857/claims.screen.for.287.pdf)
