### ISSUE TITLE
Loss and Damaged Claims Section - Rewording of Claims sentence

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#288]
Rewording of Claims sentence 

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior

_Summarize expected behavior._ Change third sentence under "Lost & Damaged Household Goods Section to read "However, if you and your Transportation Service Provider cannot reach a settlement for all or a portion of your claim, you can transfer that portion of your claim to your Military Claims Office (MCO) for processing.

## Observed Behavior

_Summarize observed behavior._"However, if you and your transportation service provider (TSP) cannot negotiate a settlement on those items, you should later transfer the claim to your Military Claims Office so that they can help."

## Steps to Reproduce

To reproduce this issue…

1. _Describe step one._
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots  Tried saving this one as a picture JPG and it still didn't allow for attaching 
![claims screen snipped for 288](https://user-images.githubusercontent.com/35501704/35011662-e40df9ea-fafe-11e7-96cc-3af6b39326e8.JPG)

_Attach relevant screenshots here._

**Comment by ERESOS73** [comment]
PDF File - Claims Screen Snipped for 288

**Comment by ERESOS73** [comment]
[Claims Screen snipped for 288.pdf](https://github.com/deptofdefense/move.mil/files/1636870/Claims.Screen.snipped.for.288.pdf)
