### ISSUE TITLE
Loss and Damaged Claims Section - Rewording of Loss and Damage Report sentence 

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#289]
Under the section titled Loss and Damage Report remove the sentence that starts with "the big advantage…

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior

_Summarize expected behavior._REMOVE  "The big advantage of filing the Loss/Damage report is that it extends the amount of time you can file claims and still receive the full replacement value."

## Observed Behavior

_Summarize observed behavior._"The big advantage of filing the Loss/Damage report is that it extends the amount of time you can file claims and still receive the full replacement value."

## Steps to Reproduce

To reproduce this issue…

1. _Describe step one._
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots......... Attach snipped sentence from Move.mil site

_Attach relevant screenshots here.
[Claims Screen snipped for 289.pdf](https://github.com/deptofdefense/move.mil/files/1636897/Claims.Screen.snipped.for.289.pdf)

**Comment by jillesmith1** [comment]
VALID--for dev action. Delete entire sentence, "The big advantage of filing the Loss/Damage report is that it extends the amount of time you can file claims and still receive the full replacement value."
