### ISSUE TITLE
Lost & Damage Claims - Damage found on Pack-Up/Delivery Day

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#290]
Rewording of Damage found on Pack-Up/Delivery Day... The DD Form 1840 is no longer the correct form #, it isn't #ed in DPS claims. 

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior

_Summarize expected behavior._Remove "Pack-up."  Remove/Change entire paragraph to read.... "Damage found on Delivery Day: You should note any obvious loss or damaged items discovered at delivery on the "Notice of Loss or Damage At Delivery" form. This form is provided to you by the delivery agent.  You will have 75 days to report any loss or damage you did not note at the time of delivery."   

## Observed Behavior  Under the section titled Damage on Pack-up/delivery day. 

_Summarize observed behavior._ "Damage found on Pack-Up/Delivery Day: If you notice any lost or damaged items on delivery day, you should ask the driver to complete and sign a DD1840 form. (The driver should have copies of this form on hand, but if you want to be super prepared, you can print a few copies yourself.) Of course you can always report these items after the fact, but the advantage of doing it on moving day is that both you and your transportation service provider (TSP) are agreeing that damage occured up front. That can lead to fewer disputes later on in the claims process and potentially higher settlements. If you and the driver complete a paper DD1840 form, a copy of this document must be uploaded to the Defense Personal Property System (DPS) within 30 days of your delivery date."

## Steps to Reproduce

To reproduce this issue…

1. _Describe step one._
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._ Not allowing an attachment screen shot..will try after submitting

**Comment by jdsager** [comment]
Attachment that wouldn't load above  [Screen shot #290.pdf](https://github.com/deptofdefense/move.mil/files/1636974/Screen.shot.290.pdf)

**Comment by jillesmith1** [comment]
Addressed with #291 
[#291 Lost or Damaged Household Goods Items.docx](https://github.com/deptofdefense/move.mil/files/1700780/291.Lost.or.Damaged.Household.Goods.Items.docx)
