### ISSUE TITLE
Loss and Damaged Claims Section - Rewording of the paragraph Pro-Tip 

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#292]
We rewording of the paragraph Pro-Tip 

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior

_Summarize expected behavior._"Pro-Tip: If you fail to submit a loss and damage report within the 75 day following delivery and have discovered loss or damage you should still file a loss and damage report in DPS.  The system will ask you why you are late.  You should contact your MCO and request a waiver.  The MCO can grant a waiver if good cause for the delay is shown.  Good cause may include, but is not limited to, officially recognized absense or hospitalization of the member during all or a portion of the period of 75 days following the date of delivery."  

## Observed Behavior

_Summarize observed behavior._Remove/replace all of the "Pro-Tip" ...."If you file a Loss/Damage Report, you can submit claims for any additional lost or damage items discovered  after the initial 75 day window even if it wasn’t included on the original Loss/Damage report." Replace it with above 
## Steps to Reproduce

To reproduce this issue…

1. _Describe step one._
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._ ATTACHED area of concern, replace paragraph with above verbiage 
[Claims Pro Tip # 292.pdf](https://github.com/deptofdefense/move.mil/files/1637048/Claims.Pro.Tip.292.pdf)

**Comment by hatueyustc** [comment]
This is a priority request by the Military Claims Services, please change

**Comment by hatueyustc** [comment]
Add label "USTC Reviewed", Danny Martinez
