### ISSUE TITLE
What to Expect with a CONUS Move - Clean Up, Claims & Customer Survey

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#294]
From our HQ Claims folks, Minor input 1st and 2nd paragraph but major changes to the third paragraph...can we get the same changes accomplished to the OCONUS area also please  

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior.....Located at the Move.mil website under “What to Expect with a CONUS Move”.  
Clean Up, Claims & Customer Survey

_Summarize expected behavior._
Unless you make an agreement with the moving company prior to them leaving the residence during the unpack, don't expect them to return for removal of any boxes, packing material, etc. after you unpack them. They are only responsible to remove it from the residence on the delivery day.

While we hope all of your items arrived in one piece, the reality is that isn't always the case. You will need to sign in to the Defense Personal Property System (DPS) and complete the claims part of the process. When you login to the system, you can expect to see two paths - Lost/Damage Report and Claims Submission.

The purpose of a Loss and Damage Report is to put the moving company on notice of your intent to file a claim for those items you discovered were missing, damaged or destroyed.  Members are expected to list missing inventory items and obvious damage to their personal property on the Notice of Loss or Damage at Delivery Form provided to you by the delivering agent.  A member has 75 days from the delivery date to note any additional loss or damage not noted at delivery. Transmitting your loss and damage report DOES NOT constitute filing a claim. Submission of the Loss/Damage Report is normally done via the DPS Claims Module.  Please note that each separate shipment must have its own Loss/Damage Report and/or claim. 

You are required to file your claim in DPS to the TSP within 9 months from the date of delivery to qualify for full replacement value protection.  If you are prepared to submit you claim in the 75 days following delivery, you do not have to file a notice of loss or damage.  Claims filed after 9 months but within 2 years qualify for limited compensation.  Filing after 2 years could result in the denial of your entire claim.  Limited exceptions apply to these timelines.  Please contact your MCO if you have any questions.  
The last and final action item you can expect from the move experience is a survey. The survey will ask some questions about your experience and we highly encourage you to be upfront and honest. The surveys are read (by humans!) and if there is a negative trend on a moving company they can be suspended temporarily or indefinitely if they are providing poor service. On the flip side, if you find a moving company that did an excellent job, please put that in the survey as well to help out your colleagues!

## Observed Behavior

_Summarize observed behavior._Clean Up, Claims & Customer Survey

Once you have emptied out all your household goods from the boxes, you should call the local moving company that delivered your goods and setup a time for them to come back out and remove any old boxes, packing material, etc. They are responsible to remove it from the residence one time after delivery. If possible, have everything piled up in one location to get this done quickly.

While we hope all of your items arrived in one piece, the reality is that isn't always the case. You will need to sign in to the Defense Personal Property System (DPS) and complete this part of the process. When you login to the system, you can expect to see two paths - Lost/Damage Report and Claims Submission.

A Loss/Damage Report is your way to notify the moving company that some of your items are missing or were damaged during the delivery process. This must be done within 75 days of your delivery date. If the items cannot be found or they cannot fix the damage, you must file a claim to be reimbursed! Remember… a Loss/Damage Report is NOT a claim!

If you did not submit a Loss/Damage Report, you will need to file your claim within 75 days of delivery. If you submitted a Loss/Damage Report within the 75 day window, you will have up to 9 months to file a claim for the Full Replacement Value of the item you are claiming. If the claim is filed more than 9 months from the delivery date, you will only be eligible for depreciated value up to two years from delivery.

The last and final action item you can expect from the move experience is a survey. The survey will ask some questions about your experience and we highly encourage you to be upfront and honest. The survey's are read (by humans!) and if there is a negative trend on a moving company they can be suspended temporarily or indefinitely if they are providing poor service. On the flip side, if you find a moving company that did an excellent job, please put that in the survey as well to help out your colleagues!

## Steps to Reproduce

To reproduce this issue…

1. _Describe step one._
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots
[Enclosure (1) (Located at conus and oconus) (4).docx](https://github.com/deptofdefense/move.mil/files/1639753/Enclosure.1.Located.at.conus.and.oconus.4.docx)

_Attach relevant screenshots here._

**Comment by jillesmith1** [comment]
VALID--for dev action. Entire text has been revised to comply with design principles. Also note the FAQs that can speak to details and the call-out for directing questions to MCOs.

Change text to read, "Your moving company is not required to return and pick up any empty boxes after they’ve delivered everything to your new home. The movers are only responsible for hauling away empty boxes and packing materials when they’re finished delivering your belongings. If you ask them to come back to take your empty boxes and they agree to do it, then that’s great! If possible, have everything piled up in one location to get this done quickly.

While we hope all of your items arrived in one piece, the reality is that isn't always the case. You will need to sign in to the Defense Personal Property System (DPS) and complete this part of the process. When you login to the system, you can expect to see two paths - Lost/Damage Report and Claims Submission.

Filling out the **Loss or Damage AT Delivery** Form lets the moving company know that some of your items were missing or damaged during the delivery process. This form must be done within 75 days of your delivery date. If the items cannot be found or they cannot fix the damage, **you must file a claim to be reimbursed!** Remember… a Loss/Damage Report is NOT a claim!
If you did not submit a Loss/Damage Report, you will need to file your claim within 75 days of delivery. If you submitted a Loss/Damage Report within the 75 day window, you will have up to 9 months to file a claim for the full replacement value of the item you are claiming. If the claim is filed more than 9 months from the delivery date, you will only be eligible for depreciated value up to two years from delivery. Contact your Military Claims Office or MCO if you have questions.
The last and final action item you can expect from the move experience is a survey. The survey will ask some questions about your experience and we highly encourage you to be upfront and honest. The surveys are read (by humans!) and if there is a negative trend on a moving company they can be suspended temporarily or indefinitely if they are providing poor service. On the flip side, if you find a moving company that did an excellent job, please put that in the survey as well to help out your colleagues!

**Comment by jkoulish-bixal** [comment]
I do not see a way to claim the issue here, but I am happy to take this one on. Hopefully will be able to get a pull request submitted later today or tomorrow.

**Comment by jkoulish-bixal** [comment]
@jillesmith1 I have updated the text in the code base to match the contents in your comment above, and should be able to submit the changes shortly. 

Two questions before I do so:
1. Do we still want to include the link to the DPS portal, as it currently appears? I will keep it in unless I hear otherwise.
2. To clarify, we want this section of the CONUS and OCONUS instructions to now be identical? If so, I will rework the code structure accordingly.

Thanks!

**Comment by jillesmith1** [comment]
Hello, @jkoulish-bixal! 
Q1:  Yes, let's keep the link to the DPS portal as it currently appears.
Q2:  Well, the information is applicable to both CONUS and OCONUS customers. From a design/flow perspective, what is the best way to point both CONUS and OCONUS customers to this information if it were presented in one spot? In other words, is it elegant to have the exact same information posted in two different spots? (Hope that makes sense; I'll monitor this for your response.)

**Comment by jkoulish-bixal** [comment]
Hi @jillesmith1! Thank you for the feedback. Per that second point, I will ultimately defer to our UX team as to the propriety of posting the same information on two different pages, but personally see no reason why it would be a problem in this case. That said, the code base is easier to manage if identical text is placed in a single file with references from each page. That way, any further changes will only need to be made once.

I will complete that change and submit a pull request shortly. For reference, here is a screenshot of that section on the CONUS page with the new text.
![image](https://user-images.githubusercontent.com/29130580/37484230-5abf08f4-285e-11e8-909f-d35851933cba.png)

**Comment by jgarber623-gov** [comment]
Resolved by #376.
