### ISSUE TITLE
FAQ's section, Delivery and "Who do we notify if they damage the home"

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#295]
Rewrite the answer for: Who do we notify if they damage the home

## Checklist

I have…

- [ ] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [ ] attached screenshots illustrating relevant behavior.

## Expected Behavior

_Summarize expected behavior._If during delivery the home is damaged it's important you record the damage in writing before the moving company leaves.  If they do not have a specific form available to record damage to the home, use the Notice of Loss or Damage At Delivery Form.

## Observed Behavior

_Summarize observed behavior._If you notice damage to your home by the movers, take a photo of the damage and reach out to the local property office’s quality control office to speak with an inspector if possible. You should also notify the lead/supervisor of the move team.

## Steps to Reproduce

To reproduce this issue…

1. _Describe step one._
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[Damage to Home change #295.pdf](https://github.com/deptofdefense/move.mil/files/1639817/Damage.to.Home.change.295.pdf)

**Comment by Elliottdotgov** [comment]
Won't change. This is contradictory to what is established best practice by JPPSOs.
