### ISSUE TITLE
Moving Guide: Rewrite of Pro-Tip addressing Power of Attorney 

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#296]
Within "Moving Guide" "Overseas Moves (OCONUS)" "Orders" then within "Move with Family", change the verbiage of the Pro-Tip: 

Recommendation by the Service's MCO 

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior

_Summarize expected behavior._ "Pro-Tip: Get a Special Power of Attorney that allows them to take necessary action on your behalf for the movement of shipment and claims filing."

## Observed Behavior

_Summarize observed behavior._Pro-Tip: Get a General Power of Attorney for your spouse. This allows them to take necessary action on moving and financial decisions while you're in the field. 

## Steps to Reproduce

To reproduce this issue…

1. _Describe step one._
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[POA Pro-Tip change #296.pdf](https://github.com/deptofdefense/move.mil/files/1640176/POA.Pro-Tip.change.296.pdf)

**Comment by jillesmith1** [comment]
VALID--for dev action. Change to "Get a Special Power of Attorney for your spouse."

**Comment by jgarber623-gov** [comment]
Also updating the same pro-tip on [the civilians page](https://www.move.mil/moving-guide/civilians).
