### ISSUE TITLE
FAQ’s page “After the Move”:  "What is the difference between a Loss and Damage report and A Claim"

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#297]
Rewording of paragraphs of this FAQ ...submitted by HQ Service's MCO, they didn't agree with the language 

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior

_Summarize expected behavior._

"A Loss/Damage Report places the TSP on notice of your intent to file a claim.   Any items not noted as lost or damaged at the time of delivery must be recorded and submitted to the TSP in the 75 days following delivery. Submission of the Loss/Damage Report is normally done via the DPS Claims Module.  Please note that each separate shipment must have its own Loss/Damage Report and claim.

The claim is your request for reimbursement.   To qualify for the full replacement value of items lost or destroyed, you must file your claim in DPS and submit it to the TSP in the nine months following delivery.  Any filing after 2 years could result in the denial of your entire claim.  

Limited exceptions apply to these timelines.  Please contact your MCO if you have any questions." 

## Observed Behavior

_Summarize observed behavior._This one can get tricky, so make sure you know the difference between the two and the overall process.

A Loss/Damage Report is your way to notify the household goods carrier (Transportation Service Provider - TSP) that some of your items are missing or were damaged during the delivery process. This must be done within 75 days of your delivery date. If the items cannot be found or they cannot fix the damage, you must file a claim to be reimbursed!

A Claim is submitted when you are requesting to be reimbursed for the loss or damage to an item.

## Steps to Reproduce

To reproduce this issue…

1. _Describe step one._
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._  Screen shot of concerned area 
[After the Move difference between loss damage report vs claim.pdf](https://github.com/deptofdefense/move.mil/files/1640248/After.the.Move.difference.between.loss.damage.report.vs.claim.pdf)

**Comment by jillesmith1** [comment]
VALID--for dev action. First sentence and paragraph 2 will remain as is IOT comply with established design principles. 

Replace third paragraph/sentence to read, "A **Claim** is made when you request reimbursement for lost or damaged items. To qualify for the full replacement value, you **must file your claim in the system (DPS) and click the "Submit" button within nine months after your household goods were delivered to you.** If you have questions about claims filing deadlines, contact your MCO (Military Claims Office)."  

Link MCO (Military Claims Office) to the MCO locator.

**Comment by rich-allen-gov** [comment]
@jillesmith1 , question on formatting. Is the bold, in the above 3rd paragraph, meant to be bold on the website as well? Or to highlight differences between the original request and what will was decided on?

**Comment by rich-allen-gov** [comment]
Also and I apologize being new to the project, but better safe than sorry,
MCO locator refers to this correct? https://www.move.mil/resources/locator-maps

**Comment by jillesmith1** [comment]
Hello, @rich-allen-gov! The bolded font was intended to be bold on the website too--UNLESS you have another (Design) way to emphasize this information for the customer.

**Comment by jillesmith1** [comment]
Sorry! @rich-allen-gov, the MCO locator should be pointing to this: https://www.move.mil/customer-service#claims.  MCO is the Military Claims Office, which is different than a "PPO" (in customer-speak, a Personal Property Office.) You can also note on the top of that page the link for "Find you local personal property office"--THAT is the _true_ locator link>

**Comment by rich-allen-gov** [comment]
No, thank you, I'm still learning the terminology so that's quite helpful. As for the bold, I figured it was meant to be that way, just being sure!
