### ISSUE TITLE
FAQ’s page “After the Move”: "How do I file a Loss/Damage report"

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#298]
Reword FAQ on how to file a loss/damage report... Submitted by HQ Service Claims 

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior

_Summarize expected behavior._  "You are required to report all loss and damage to the Transportation Service Provider (TSP) within 75 days of the date of delivery to qualify for reimbursement of your missing or damaged items.  The preferred way to make your report is to use the DPS program.  Once you have entered the required data listing all your loss and damage, you MUST CLICK the “SUBMIT” button to properly transmit your notification of loss or damage to the TSP.  Transmitting your loss and damage report does not constitute the filing of a claim. Please note that in most cases each separate shipment will have its own Government Bill of Lading (GBL) number.  Be sure to choose the correct GBL number when submitting your Loss/Damage Report and/or claim.
You also may submit your “Notification of Loss/Damage after Delivery” form to the TSP by mail, FAX or by attaching the form to an email and sending it to the TSP.  The form should have been given to you by the TSP at the time of delivery.  If you elect to submit the form using one of these methods, you must dispatch it to the TSP by the 75th day following delivery, and you should ensure that you save some proof of dispatch, e.g., return receipt, FAX confirmation sheet, or email delivery receipt.  If you had good cause to exceed the 75-day notice period, such as an officially recognized absence or hospitalization during all or a portion of the time period, please pass this information to your TSP for their consideration.  In these cases, your TSP is required to contact your Military Claims Office (MCO) for a determination."

## Observed Behavior

_Summarize observed behavior._You have a couple of methods to submit this type of report. You can use the same online system you used to book your move to file this report. It’s located under the Claims tab. You may also submit your "Notification of Loss/Damage after Delivery" form to the TSP by mail or FAX or by attaching the form to an email and sending it to the TSP. The form should have been given to you by the TSP at the time of delivery. As with anything this important, make sure you request a delivery receipt! Reminder - you have 75 days from the date of delivery to accomplish this task!

## Steps to Reproduce

To reproduce this issue…

1. _Describe step one._
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[FAQ How to file the loss damage report.pdf](https://github.com/deptofdefense/move.mil/files/1640312/FAQ.How.to.file.the.loss.damage.report.pdf)

**Comment by jillesmith1** [comment]
VALID and relates to #299. This issue re-write is not a singular FAQ. MCO's paragraph was broken down into 4 distinct FAQs.

1.  **How do I file a Loss/Damage Report?** 

The preferred way to file your loss and damage report is to do it in the system (DPS).  After you've entered all of the required information and listed the loss and damage per item, you MUST CLICK the “SUBMIT” button to transmit the Loss/Damage Report to the TSP. **Remember, transmitting your loss and damage report does NOT mean you've filed your claim!**  Also, note that in most cases each separate shipment will have its own Government Bill of Lading or GBL number. Be sure to choose the right GBL number for that shipment when submitting your Loss/Damage Report (and when submitting your claim--when you're ready for that step.)

2.  **Is there a deadline for submitting my Loss/Damage Report?**  

Yes! You must report all loss and damage to the Transportation Service Provider (TSP) within 75 days of the date of delivery to be reimbursed for those missing or damaged items. 

3.  **Are there any other ways I can send in my Loss/Damage form if I can't access the system (DPS)?**

Yes, you can submit your “Notification of Loss/Damage after Delivery” form to your TSP by mail, FAX, or by attaching the form to an email and e-mailing it to your TSP. The TSP should have given you this form when they delivered your household goods to your new home. Whichever way you choose to get the Loss/Damage Report form to your TSP, make sure the TSP receives it before the 75th day following delivery of your household goods to your new home. It's a good idea to keep your proof of dispatch, i.e., a return mail or certified letter receipt, FAX confirmation sheet, email delivery confirmation, or email "read" receipt. 

4.  **Can I still submit my Loss/Damage Report notification if I missed getting it to the TSP before the 75th day?**

If you had good cause to exceed the 75-day notice period, such as an officially recognized absence or hospitalization during all or a portion of that 75-day window, please pass that information to your TSP for their consideration. When incidents like this happen, your TSP is required to contact your Military Claims Office (MCO) for a determination.
