### ISSUE TITLE
FAQ: What are some of the items that will be needed for the claim?  

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#300]
Rewording of answer:  What are some of the items that will be needed for the claim?  

## Checklist

I have…

- [ ] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [ ] attached screenshots illustrating relevant behavior.

## Expected Behavior

_Summarize expected behavior._  rewrite to "The TSP will be responsible for paying for repair estimates required to process claims that are filed with the TSP.  You should request a copy of this estimate from the TSP before accepting settlement on your claim.  

The TSP or MCO (should the claim be transferred) may request additional information from you to better substantiate your claim.  You are responsible for substantiating ownership or possession and prove the item was tendered to the TSP.  Tender is usually proven by the inventory prepared at origin.  That is why it is important you take the time at origin to review the inventory before signing and ensure all your high value items are properly listed on the high value inventory.  

The TSP may request you provide substantiation of the replacement cost value for missing or destroyed items.  This can usually be accomplished by locating a replacement cost clipping in your local newspaper or online.  

For high value items, you may receive a request for proof of value.  This can usually be accomplished by providing a copy of the original receipt, credit card statement of account or cancelled check.  If you have had the item appraised, this too would assist with substantiating value.
If you have any concerns or questions about request from a TSP, please contact your MCO."

## Observed Behavior

_Summarize observed behavior._ Replace paragraphs  
[FAQ items needed for claim.pdf](https://github.com/deptofdefense/move.mil/files/1640402/FAQ.items.needed.for.claim.pdf)
 "When filing a claim, it’s recommended that you have before/after pictures of the item that you are claiming. Additionally, any receipts, quotes for repair and any other documentation that show what the value of the item was at the time of purchase is very helpful. The repair quotes are also useful to the claims team when determining how much you will get back. One final tip – make sure when you sign off on the inventory sheet prior to your items being loaded up on the truck that the remarks the movers indicated for each item are correct… your brand new/undamaged dining room table should not have a remark that says it’s full of scratches, etc."

## Steps to Reproduce

To reproduce this issue…

1. _Describe step one._
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._  
[FAQ items needed for claim.pdf](https://github.com/deptofdefense/move.mil/files/1640403/FAQ.items.needed.for.claim.pdf)

**Comment by hatueyustc** [comment]
Add "USTC Reviewed" label.  Approved with changes:

"When filing a claim, it’s recommended that you have before/after pictures of the item that you are claiming. Additionally, any receipts, quotes for repair and any other documentation that show what the value of the item is very helpful. This can usually be accomplished by locating a replacement cost clipping in your local newspaper or online. Repair estimates are also useful to the claims team when determining how much you will get back.  The mover is responsible for paying for repair estimates so you should request a copy of this estimate from before accepting settlement on your claim.  For high value items, you may receive a request for proof of value. This can usually be accomplished by providing a copy of the original receipt, credit card statement of account or cancelled check. If you have had the item appraised, this too would assist with substantiating value.  Also– make sure when you sign off on the inventory sheet prior to your items being loaded up on the truck that you take the time to review the inventory before signing and ensure all your items are listed (including high value items on a high value inventory).  One final tip - be sure the remarks the movers indicated for each item are correct… your brand new/undamaged dining room table should not have a remark that says it’s full of scratches, etc."
