### ISSUE TITLE
FAQ  The transportation provider and I cannot agree on a claim amount…who do I contact for help? 

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#301]
Rewrite of FAQ Title and paragraphs for "The transportation provider and I cannot agree on a claim amount…who do I contact for help?"  

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior

_Summarize expected behavior._  Rewrite title to: The Transportation Service Provider and I cannot agree on an offer amount…who do I contact for help? 

Rewrite paragraphs to: "The FRV program protection provides for the lesser of the repair or replacement cost of an individual item.  The TSP, at its option, can arrange for the repair of the item or replace the item with an item of like kind and quality or, provide an equivalent cash settlement for the item.  The TSP is required to document the offer on each line item in DPS.  Your options are to accept the offer, make a counter offer or transfer the line item or your entire claim to the MCO.   

If you cannot reach a mutually acceptable settlement directly with the TSP on your entire claim, you can accept payment from the TSP on those line items on which you and the TSP have reached agreement and transfer the remaining line items to the MCO.   The TSP will then pay you on the items on which you have reached an agreement.  Once you have accepted the TSP’s offers in DPS, it is recommend that you send an email to the TSP notifying them that you have accepted the offers in DPS. The TSP has 30 days from the date of your acceptance in DPS to issue a check.

Should you have any questions or concerns about any offer, it is recommended you contact your MCO or TSP directly.  If you have any concerns about signing a settlement agreement that indicates the offer is in full and final settlement of your entire claim, contact your MCO.  
 
Transferring your claim to the MCO: 30 days after you have submitted your consolidated claim to the TSP, you have the option of transferring your claim to your MCO and still be eligible for Full Replacement Value (FRV).  Please be aware that your MCO can only provide limited compensation to you; however your MCO will assert an FRV claim against your TSP.  If your MCO recovers additional monies above what you were paid initially, that amount will be passed along to you.  If you have questions, please contact your MCO. 

Special note for Army and AF Personnel: It is requested that you contact your MCO to advise you have transferred the claim in DPS. They will advise of additional requirements needed to complete the transfer. " 

## Observed Behavior

_Summarize observed behavior._  Rewording of title "The transportation provider and I cannot agree on a claim amount…who do I contact for help?"

Replace..."If you and the transportation provider go back and forth and you cannot come to an agreement on the offer they are providing you then you’ll need to contact your Military Claims Office. They will help advocate on your behalf, but be prepared to re-submit all your documentation through their system."
## Steps to Reproduce

To reproduce this issue…

1. _Describe step one._
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[Transportation Service Provider and I cannot agree on a offer amount…..pdf](https://github.com/deptofdefense/move.mil/files/1640441/Transportation.Service.Provider.and.I.cannot.agree.on.a.offer.amount.pdf)

**Comment by schustdj** [comment]
Is there a way to distill these proposed paragraphs? They are lengthy, and possess verbiage/acronyms that would frustrate the average joe. Is the purpose of the site about giving fairly decent advice & starting points, or is it a detailed rewrite of policy documents?

**Comment by jdsager** [comment]
"Is the purpose of the site about giving fairly decent advice & starting points, or is it a detailed rewrite of policy documents" ... That's where the problem is, where it was written the first time on the website... There is STRICT policy that needs to be followed for the claim to be settled properly.  "Fairly decent advice & starting points" gets us in trouble where the customers takes that verbiage and argues with the Claims office because they've "found it on a official DoD website" so they are led to believe it is totally correct.

**Comment by hatueyustc** [comment]
Close, additional FAQs need to be developed as the information provided here is accurate and from the Military Claims Office, but too lengthy.  These really should be developed into separate FAQs.  Leave existing FAQ as is.

**Comment by jdsager** [comment]
Maybe the expected behavior should be provided in a new area if it isn't going to be approved for change

**Comment by jillesmith1** [comment]
CLOSE--language on the site points customer to the appropriate spot--the MCO.
