### ISSUE TITLE
Under "Moving Guide"  At Your Destination:  "Document and report any damage to your TSP as it comes in the house"

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#302]
Under "Moving Guide" "Moving Tips" "At Your Destination" last item...:  "Document and report any damage to your TSP as it comes in the house"

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior

_Summarize expected behavior._:  Title/Subject change to "Document and report any obvious loss or damage to your personal property as it is delivered into the home"

Answer change to "You are expected to list missing inventory line items and obvious damage to your personal property on the Notice of Loss or Damage At Delivery Form provided to you by the delivering agent.   It is your responsibility to ensure obvious loss and damage is noted on this form.  You will simply list the inventory number, description and loss or damage.  For example:  inv #101 (Piano) missing; Box 45 (kitchen items) crushed; #236 (TV Stand) broken in half; inventory #36 (mattress) not in carton, greasy fingerprints.   

Remember you have 75 days to unpack and inspect your property and report any loss or damage to the TSP.   
As things are unpacked photograph the damage or condition the carton was packed. This type of proof can be uploaded in DPS when filing your claim and will assist with the claims process.   Finally, if the delivery crew caused any damage to your home, rental unit, base housing, etc., please be sure to make them aware immediately, preferably before they leave your home.    The 75 day period does not apply to this type of damage.  You can document this damage on the inventory or on the Notice of Loss/Damage At Delivery form.  This type of damage is handled between you and the TSP as your military claims office has no legal authority to pay such claims."

## Observed Behavior

_Summarize observed behavior._ Rewrite of subject/title and following paragraph from "Footprints on your mattress, nicks in your table leg? As things are unpacked photograph any damage immediately. Also, make sure you point out this damage to the truck driver - ask them to document the damage as well. This can help with any claims negotiations later on."

## Steps to Reproduce

To reproduce this issue…

1. _Describe step one._
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._  attach
[Document As it comes in the house 302.pdf](https://github.com/deptofdefense/move.mil/files/1640535/Document.As.it.comes.in.the.house.302.pdf)

**Comment by hatueyustc** [comment]
Approved with change, please add "USTC Reviewed" label.  Update as follows:

"Footprints on your mattress, nicks in your table leg? As things are unpacked photograph any damage to the item and how it was packed in the carton immediately. Also, make sure you point out this damage to the truck driver - and that you document the damage on the Notice of Loss or Damage At Delivery Form provided to you by the delivering agent. Simply list the inventory number, description and whether it was missing or damaged. For example: #101 (Piano) missing; #45 (box with kitchen items) crushed; #236 (TV Stand) broken in half; inventory #36 (mattress) not in carton, greasy fingerprints.  This can help with any claims negotiations later on."
