### ISSUE TITLE
Lackland weigh scales need to be removed 

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#305]
There is no weigh scales available at Lackland, looks to be Laughlin's 

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior

_Summarize expected behavior._  Remove weigh scales for Lackland ...attached screen shot what needs to be removed 

## Observed Behavior

_Summarize observed behavior._  Weigh scales for Lackland false information, there is none 

## Steps to Reproduce

To reproduce this issue…

1. _Describe step one._
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[Lackland AFB Scale.pdf](https://github.com/deptofdefense/move.mil/files/1643257/Lackland.AFB.Scale.pdf)

**Comment by jdsager** [comment]
the Lackland AFB Scale is still showing when Lackland is entered first on the locator ...can we get it removed totally please

**Comment by jgarber623-gov** [comment]
@jdsager The change will go out to move.mil when we next push to production.

**Comment by jdsager** [comment]
Thank you, how often or when is the next push to production?  Didn't know that about some needing pushed that way ...I see some changes as you was going along, thought they all work that way, got it, some more complicated

**Comment by jgarber623-gov** [comment]
@jdsager Frequency of production pushes depends on what's changing and the complexity of those changes. We don't have a specific schedule, but respective to this particular issue, we'll probably do a push in the next few hours.

Thanks for helping us improve the accuracy of information on move.mil!
