### ISSUE TITLE
Fort Belvoir PPPO not in Locator 

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#307]
Within "Tools & Resources" "Find Nearby locations." When the zip 22060 or Fort Belvoir, VA is entered in Locator, the Fort Belvoir PPPO does not come up.  

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [ ] attached screenshots illustrating relevant behavior.

## Expected Behavior

_Summarize expected behavior._ When entering zip 22060 or Fort Belvoir, VA in Locator, the Fort Belvoir PPPO should come up as such:    
"PPPO Fort Belvoir/ Logistics Readiness Center (LRC)
9910 Tracy Loop, Building # 766,
406th Army Field Support Battalion (AFSB) Army Sustainment Command (ASC) 
Fort Belvoir, VA 
Our hours  0800 - 1130 hrs 1230 - 1500 hrs Closed for lunch 1200-1230 hrs. Closed Friday Afternoon  
(703) 805-5674 Customer Service (voice) usarmy.belvoir.mbx.outboundpcsing@mail.mil"

## Observed Behavior

_Summarize observed behavior._ PPPO information missing 

## Steps to Reproduce

To reproduce this issue

Within "Tools & Resources" "Find Nearby locations."  Enter the zip 22060 or Fort Belvoir, VA

1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._

**Comment by jillesmith1** [comment]
for dev
