### ISSUE TITLE
Add links to "It's Your Move" and "POV" DTR attachments also 

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#312]
Submitted by USTC J54 PI office - Either under the “Helpful Links” or “Plan Your Move” sections place links to applicable attachments all DoD customers need to read to prepare for their moves

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior

_Summarize expected behavior._ (In attachment also) Either under the “Helpful Links” or “Plan Your Move” sections place links to applicable attachments all DoD customers need to read to prepare for their moves

Attachment K1:  “It’s Your Move” Armed Forces Members (Military Members)
https://www.ustranscom.mil/dtr/part-iv/dtr_part_iv_app_k_1.pdf

Attachment K2:  “It’s Your Move” Department of Defense (DoD) Civilian Employees
https://www.ustranscom.mil/dtr/part-iv/dtr_part_iv_app_k_2.pdf

Attachment K3:  Shipping Your POV
https://www.ustranscom.mil/dtr/part-iv/dtr_part_iv_app_k_3.pdf

Attachment K4:  Storing Your POV
https://www.ustranscom.mil/dtr/part-iv/dtr_part_iv_app_k_4.pdf

## Observed Behavior

_Summarize observed behavior._  Request links be added to further assist customers 

## Steps to Reproduce

To reproduce this issue…

1. _Describe step one._
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[GitHub # 312    Add links to It's Your Move and POV DTR attachments also.docx](https://github.com/deptofdefense/move.mil/files/1647296/GitHub.312.Add.links.to.It.s.Your.Move.and.POV.DTR.attachments.also.docx)

**Comment by hatueyustc** [comment]
Approved, please add label "USTC Reviewed."  Note, these are the only DTR sections written for the "DoD customer" directly.
