### ISSUE TITLE
PPM 2nd paragraph verbiage change 

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#313]
Submitted by USTC J54 PI:  Located at: Moving Guide - Moving with the Military Overview - Move Types - PPM Section - 2nd paragraph rewrite ... ADD "or perform your own move" end of 1st sentence. Add ", not to exceed your authorized weight allowance" end of 3rd sentence. And input "Military" before Service in last sentence 

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [ ] attached screenshots illustrating relevant behavior.

## Expected Behavior - 2nd paragraph rewrite ... ADD "or perform your own move" end of 1st sentence. Add ", not to exceed your authorized weight allowance" end of 3rd sentence. And input "Military" before Service in last sentence ...Summarize expected behavior paragraph below has the changes as requested 

_Summarize expected behavior._  As an incentive to move yourself, the government will pay you 95% of their cost to hire a moving company on your behalf or perform your own move. If you can move your belongings yourself for less money, you get to keep the difference. Remember, this money is considered an incentive and is based on the household goods weight you actually transport, not to exceed your authorized weight allowance. If necessary, for most branches of Military Service you can receive an advance payment of up to 60% of the incentive value. Calculate your estimated PPM incentive for an upcoming move.

## Observed Behavior

_Summarize observed behavior._ As an incentive to move yourself, the government will pay you 95% of their cost to hire a moving company on your behalf. If you can move your belongings yourself for less money, you get to keep the difference. Remember, this money is considered an incentive and is based on the household goods weight you actually transport. If necessary, for most branches of service you can receive an advance payment of up to 60% of the incentive value. Calculate your estimated PPM incentive for an upcoming move.

## Steps to Reproduce

To reproduce this issue…

1. _Describe step one._
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._

**Comment by hatueyustc** [comment]
Approved, please add label "USTC Reviewed."
