### ISSUE TITLE
Rewrite of NOTE at the bottom of PPM Estimator

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#314]
Submitted by USTC J54 PI: Located at:  Tools & Resources -  Personally Procured Move (PPM) Estimator - NOTE at the bottom of the page ...rewrite of the note  "off the daily rates available when you schedule your move in DPS. Rates vary based on transporter availability, "

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior Rewrite to:  "Note: This tool only provides an estimate of what you might receive if you decide to do a personally procured move. Your actual incentive payment will be calculated based on  the selected move date (Peak vs. Non-Peak Season), distance traveled, and the actual weight of the shipment"

_Summarize expected behavior._

## Observed Behavior - Note: This tool only provides an estimate of what you might receive if you decide to do a personally procured move. Your actual incentive will be calculated based off the daily rates available when you schedule your move in DPS. Rates vary based on transporter availability, selected move date (Peak vs. Non-Peak Season), distance traveled, and the actual weight of the shipment. 

_Summarize observed behavior._

## Steps to Reproduce

To reproduce this issue…

1. _Located at:  Tools & Resources -  Personally Procured Move (PPM) Estimator - NOTE at the bottom of the page
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[GitHub # 314  Calculate My Estimate  NOTE need verbiage change.pdf](https://github.com/deptofdefense/move.mil/files/1647461/GitHub.314.Calculate.My.Estimate.NOTE.need.verbiage.change.pdf)

**Comment by jillesmith1** [comment]
Updated.

**Comment by jgarber623-gov** [comment]
Closing per @jillesmith1's [comment](#issuecomment-359051660).

**Comment by jdsager** [comment]
I don't know why this was closed as the change requested has not been changed ...what is "Updated - please Close" suppose to mean jillesmith1
