### ISSUE TITLE
Remove paragraphs below PPM for OCONUS referring to 100% reimbursement 

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#315]
Submitted by USTC J54 PI: Located under Moving Guide - Moving with the Military Overview – Move Types - Personally Procured Move (PPM) – Approved for – OCONUS - 

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior - Remove both paragraphs as highlighted in yellow on the attached 

_Summarize expected behavior._

## Observed Behavior - According to USTC J54 PI, this is inaccurate information, please remove both paragraphs "*PPMs for OCONUS Permanent Change of Duty Station Moves are generally reserved for situations where the government does not have the resources to arrange a household goods move. These moves are reimbursed at 100% of the actual cost.
lightbulb icon - Did You Know: If the government cannot arrange a Household Goods (HHG) move within the timeframe requested, you can do a PPM and receive reimbursement 100% of the actual cost associated with hiring a commercial moving company. "

_Summarize observed behavior._

## Steps to Reproduce

To reproduce this issue…

1. _Moving Guide - Moving with the Military Overview – Move Types - Personally Procured Move (PPM) – Approved for – OCONUS - 
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[PPM para note change GitHub # 315.pdf](https://github.com/deptofdefense/move.mil/files/1647494/PPM.para.note.change.GitHub.315.pdf)

**Comment by hatueyustc** [comment]
Add "USTC Reviewed" label.  The information is inaccurate. Update as follows:
Paragraph 1, DELETE the last sentence "These moves are reimbursed at 100% of the actual cost."

"*PPMs for OCONUS Permanent Change of Duty Station Moves are generally more complicated and require DoD customers to handle customs and other complex requirements and are generally reserved for situations where the government does not have the resources to arrange a household goods move."

Paragraph 2, update wording:
lightbulb icon - Did You Know: If the government cannot arrange a Household Goods (HHG) move within the timeframe requested, you can do a PPM and in some cases receive reimbursement of the actual cost associated with hiring a commercial moving company if approved in advance by your military service. "
