### ISSUE TITLE
Fix one letter in acroynm (UB) 

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#316]
Submitted by USTC J54 PI: Located under Moving Guide - Moving with the Military Overview – Move Types - Unaccompanied Baggage:

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior  Change (UG) to (UB) within the first part of the sentence "Unaccompanied baggage (UB) is an option......" 

_Summarize expected behavior._

## Observed Behavior  Currently "Unaccompanied baggage (UG) is an option..."

_Summarize observed behavior._

## Steps to Reproduce

To reproduce this issue…

1. _Located under Moving Guide - Moving with the Military Overview – Move Types - Unaccompanied Baggage
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[UB correction #316.pdf](https://github.com/deptofdefense/move.mil/files/1647537/UB.correction.316.pdf)

**Comment by jillesmith1** [comment]
For dev action.
