### ISSUE TITLE
Remove last sentence within Prepping the Move "Do Not Pack" room 

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#318]
Located at: Moving Guide-Moving Tips- Prepping the Move...10th or Last Issue titled: "Block off a special “Do Not Pack” spot for any items you will need on your road trip or deem special"

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior - Remove last sentence as it pertains to Pro-gear "This goes for professional gear (dubbed "Pro-Gear" or PBP&E)... this is typically the members' and their spouses' uniforms, professional books and papers required to perform their job."

_Summarize expected behavior._

## Observed Behavior Paragraph currently "Any items that you’ll need on your road trip or items that you deem special should be separated from the packers. Whether that means you put these items in your car or a closet in the house with a sign taped to the door "Do Not Pack" - make sure they know so your car keys don’t end up in a moving box. This goes for professional gear (dubbed "Pro-Gear" or PBP&E)... this is typically the members' and their spouses' uniforms, professional books and papers required to perform their job. "

_Summarize observed behavior._

## Steps to Reproduce

To reproduce this issue…

1. _Located at: Moving Guide-Moving Tips- Prepping the Move...Under: "Block off a special “Do Not Pack” spot for any items you will need on your road trip or deem special"
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[Prepping the Move - Do not Pack GitHub # 318.pdf](https://github.com/deptofdefense/move.mil/files/1647951/Prepping.the.Move.-.Do.not.Pack.GitHub.318.pdf)

**Comment by hatueyustc** [comment]
Approved, please add "USTC Reviewed" label.
