### ISSUE TITLE
Don’t move still packed boxes from your previous move – you probably don’t need them.

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#319]
Moving Guide - Moving Tips - Prepping the Move - 8th subject down "Don’t move still packed boxes from your previous move – you probably don’t need them."

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior ' Reword to  "The number one tip professional organizers like to give is: if you haven’t used an item in two years, you don’t need it anymore. This especially applies to those brown cardboard boxes of stuff from the past four duty stations that you never unpacked. Let’em go.  Since military families move every 2.5 years, this means that if you haven’t used an item in your current house, you are probably not going to need it in your next house (this may not apply to packed clothing appropriate for specific climates, e.g., winter clothing while your stationed in Hawaii)."

_Summarize expected behavior._

## Observed Behavior  Request rewording of "The number one tip professional organizers like to give is: if you haven’t used an item in two years, you don’t need it anymore. Since military families move every 2.5 years, this means that if you haven’t used an item in your current house, you are probably not going to need it in your next house. This especially applies to those brown cardboard boxes of stuff from the past four duty stations that you never unpacked. Let 'em go. (Unless you are moving away from Okinawa or Hawaii or Florida—then you really are going to need your winter coats.)"

_Summarize observed behavior._

## Steps to Reproduce

To reproduce this issue…

1. _Located at: Moving Guide - Moving Tips - Prepping the Move - 8th subject down "Don’t move still packed boxes from your previous move – you probably don’t need them."
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[Pack day # 319.pdf](https://github.com/deptofdefense/move.mil/files/1648047/Pack.day.319.pdf)

**Comment by hatueyustc** [comment]
Close, no action needed

**Comment by jdsager** [comment]
fine, closing it since didn't like others opinion for change
