### ISSUE TITLE
Minor verbiage change "Take time to pre-clean the new bathroon and kitchen"

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#320]
Located at: Moving Guide - Moving Tips - At Your Destination- 2nd one down "Take time to pre-clean the new bathroon and kitchen"

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior - Reword to: "Yes, yes, the previous tenants were supposed to remove all physical evidence that they lived in your new place. Allow enough time to clean before the movers arrive with all your belongings. Bonus if you brought any cleaning "leftovers" from your previous place. It makes the unpacking go easier."

_Summarize expected behavior._

## Observed Behavior:   Yes, yes, the previous tenants were supposed to remove all physical evidence that they ever lived in your new place. They never do. So allow enough time to clean before the movers arrive with all your stuff. Bonus if you took any cleaning "leftovers" from your previous place. It makes the unpacking go easier. 

_Summarize observed behavior._

## Steps to Reproduce

To reproduce this issue…

1. _ Located at: "Moving Guide - Moving Tips - At Your Destination- 2nd one down "Take time to pre-clean the new bathroon and kitchen"
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[Allow time for cleaning new home GitHub # 320.pdf](https://github.com/deptofdefense/move.mil/files/1652513/Allow.time.for.cleaning.new.home.GitHub.320.pdf)

**Comment by hatueyustc** [comment]
Close, no action needed.

**Comment by jdsager** [comment]
based on Jill and Danny's inputs, fine, close it
