### ISSUE TITLE
Para rewrite "Save any crates you got with your move - you will need to reuse it on your next move"  

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#322]
Moving Guide - Moving Tips - At Your Destination - 6th one down tilted "Save any crates you got with your move - you will need to reuse it on your next move"  

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior - rewrite to "Did you have something “crated” up for this most recent move... maybe a TempurPedic mattress or your priceless painting? That’s awesome! But wait... don’t toss that crate in the garbage or use it as the base for your kid's fort. You can keep that crate for future moves! " 

_Summarize expected behavior._

## Observed Behavior- "Did you have something “crated” up for this most recent move... maybe a TempurPedic mattress or your priceless painting? That’s awesome and hopefully it arrived in one piece when you got to your new place. But wait... don’t toss that crate in the garbage or use it as the base for your kid's fort. You actually need to KEEP that crate for future moves. The government will only pay for one crate and if you request one for that same painting in the future they may deny it... so you would have to pay the bill!"

_Summarize observed behavior._

## Steps to Reproduce

To reproduce this issue…

1. _ Located at "Moving Guide - Moving Tips - At Your Destination - 6th one down tilted "Save any crates you got with your move - you will need to reuse it on your next move" 
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[Save any crates you got with your move - you will need to reuse it on your next move  GitHub # 322.pdf](https://github.com/deptofdefense/move.mil/files/1652689/Save.any.crates.you.got.with.your.move.-.you.will.need.to.reuse.it.on.your.next.move.GitHub.322.pdf)

**Comment by jillesmith1** [comment]
ELEVATE--for TCJ4-H decision.

**Comment by hatueyustc** [comment]
Approved with a minor rewrite.  Please add label "USTC Reviewed" and rewrite to "Did you have something “crated” up for this most recent move... maybe a TempurPedic mattress or your priceless painting? That’s awesome! But wait... don’t toss that crate in the garbage or use it as the base for your kid's fort. You can KEEP that crate for future moves! The government pays a separate fee for each crate built and if you request one for that same painting in the future they may deny it."
