### ISSUE TITLE
One word "not" inserted makes the difference for "Assignment Notification" paragraph 

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#324]
Moving with the Military Overview ->What to Expect with a CONUS Move - Assignment Notification – One word “not” needs added to the 2nd to last sentence to make the paragraph correct 

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior   rewrite to include "not" The one constant within the Department of Defense is change, so we caution you to **not** make any permanent decisions (i.e. home purchase) until there are orders in hand. 

_Summarize expected behavior._ 

## Observed Behavior -  The one constant within the Department of Defense is change, so we caution you to make any permanent decisions (i.e. home purchase) until there are orders in hand.

_Summarize observed behavior._

## Steps to Reproduce

To reproduce this issue…

1. _Moving with the Military Overview ->What to Expect with a CONUS Move - Assignment Notification – One word “not” needs added to the 2nd to last sentence to make the paragraph correct 

1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[NOT make any   GitHub # 324.pdf](https://github.com/deptofdefense/move.mil/files/1652754/NOT.make.any.GitHub.324.pdf)

**Comment by hatueyustc** [comment]
Approved, please add label "USTC Reviewed."
