### ISSUE TITLE
Remove 1st sentence in "Orders" and rewrite 3rd sentence 

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#325]
Moving with the Military Overview ->What to Expect with a CONUS Move - Orders paragraph remove 1 st sentence, rewrite 3rd sentence 

## Checklist

I have…

- [ ] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [ ] attached screenshots illustrating relevant behavior.

## Expected Behavior  Remove 1st sentence "After days, weeks and potentially months of waiting you now have your orders." ....(as it is unnecessary negative connataton adding no value)   

Reword 3rd sentence to"In addition to the administrative details (e.g., your name, correct rank/grade, etc.), make sure it has the correct duty stations, dependent information and reporting dates." 

_Summarize expected behavior._

## Observed Behavior  -  Orders   
After days, weeks and potentially months of waiting you now have your orders. Your orders are an important document to have, so make sure everything is accurate. In addition to the administrative details (your name, social security number, etc.), make sure it has the correct duty station, dependent information and reporting dates. If you see anything that does not look right, you need to let the administration section know that there is an error so it can be corrected as soon as possible. Once you have your orders, you can sign in to DPS to schedule your move.

_Summarize observed behavior._

## Steps to Reproduce

To reproduce this issue…

1. _ Moving with the Military Overview ->What to Expect with a CONUS Move - Orders paragraph remove 1 st sentence, rewrite 3rd sentence 
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[Orders #325 remove 1st sent . reword 3rd.pdf](https://github.com/deptofdefense/move.mil/files/1652834/Orders.325.remove.1st.sent.reword.3rd.pdf)

**Comment by jillesmith1** [comment]
CLOSE (opinion/no action required.)

**Comment by hatueyustc** [comment]
Partially approved, add USTC Reviewed label.  Approve changing the content in the third sentence to remove "...social security number" and replace with "...correct rank/grade. New sentence would read "In addition to the administrative details (e.g., your name, correct rank/grade, etc.), make sure it has the correct duty stations, dependent information and reporting dates."

**Comment by jgarber623-gov** [comment]
@jillesmith1 @hatueyustc We've got conflicting action recommendations. Can you clarify?

**Comment by jdsager** [comment]
hatueyustc not available rest of the week but his note takes precedence 

Partially approved, add USTC Reviewed label. Approve changing the content in the third sentence to remove "...social security number" and replace with "...correct rank/grade. New sentence would read "In addition to the administrative details (e.g., your name, correct rank/grade, etc.), make sure it has the correct duty stations, dependent information and reporting dates."

**Comment by jillesmith1** [comment]
**Big negative**, jdsager. CLOSE (opinion/no action required--may change later.)

**Comment by jdsager** [comment]
I don't get it...we trying to save work here now and fix later maybe...  "opinion/no action required--may change later.)"
