### ISSUE TITLE
Remove "RV" from Special items within "Scheduling the Move"

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#326]
USTC 54-PI input:  Located at "Moving Guide - Moving with the Military Overview - Destination Matters - What to expect for a CONUS move - Scheduling the Move - within 5th item down...remove  "RV" as MOST do not qualify to be moved  

## Checklist

I have…

- [ ] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [ ] attached screenshots illustrating relevant behavior.

## Expected Behavior - Remove "RV" with  "Special items (boat, guns,  RV, large electronics)"

_Summarize expected behavior._

## Observed Behavior - "Special items (boat, guns,  RV, large electronics)"

_Summarize observed behavior._

## Steps to Reproduce

To reproduce this issue…

1. _  Located at "Moving Guide - Moving with the Military Overview - Destination Matters - What to expect for a CONUS move - Scheduling the Move
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[Remove  RV  GitHub # 326.pdf](https://github.com/deptofdefense/move.mil/files/1653233/Remove.RV.GitHub.326.pdf)

**Comment by hatueyustc** [comment]
Approved, please add USTC Reviewed label. DPS does not ask about RVs, and RVs are not typically moved.  DPS does ask about mobile homes and boats. Unfortunately customers often believe they can have their RVs moved and including here will add to confusion.

**Comment by jillesmith1** [comment]
CLOSE. Move.mil is not a replacement for entitlement counseling. PPPOs, JPPSOs, and/or Service HQs representatives should be able to address customers' questions re: unique HHG items.

**Comment by jillesmith1** [comment]
Concur--remove RV mention.

**Comment by jdsager** [comment]
Ms Smith, You Concur--remove RV mention....but you closed it before it was worked?
