### ISSUE TITLE
Rewording of 3rd para of "Before the Packers Arrive"

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#327]
Located at "Moving Guide - Moving with the Military Overview - Destination Matters - What to expect for a CONUS move - Before the Packers Arrive:   Rewording of 3rd paragraph down

## Checklist

I have…

- [ ] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [ ] attached screenshots illustrating relevant behavior.

## Expected Behavior - Rewording of 3rd paragraph down: "Additionally, you can expect a representative of the moving company  to call or come by your residence  to complete a Pre-Move Survey. During the survey, they will also complete their own weight estimation and annotate any special items that you identified when you arranged your move in the Defense Personal Property System (DPS). If you are within a week of your move and a survey has not been completed on your home, it's highly recommended that you reach out to the moving company or your local Personal Property Processing Office (PPPO) for assistance."

_Summarize expected behavior._

## Observed Behavior - "Additionally, you can expect the shipping company to send over someone to complete a Pre-Move Survey at your home. During the survey, they will also complete their own weight estimation and annotate any special items that you called out in the Defense Personal Property System (DPS). If you are within a week of your move and a survey has not been completed on your home, it's highly recommended you reach out to the moving company or your local personal property office (PPPO)."

_Summarize observed behavior._

## Steps to Reproduce

To reproduce this issue…

1. _ Located at "Moving Guide - Moving with the Military Overview - Destination Matters - What to expect for a CONUS move - Before the Packers Arrive:   Rewording of 3rd paragraph down
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[Before packers Arrive GitHub # 327.pdf](https://github.com/deptofdefense/move.mil/files/1653274/Before.packers.Arrive.GitHub.327.pdf)

**Comment by hatueyustc** [comment]
Change approved, please add USTC Reviewed label.  Note, an alternative is to remove the acronym PPPO but if it's going to be displayed then it should read Personal Property Processing Office (PPPO).

**Comment by jillesmith1** [comment]
VALID--for dev action. For simplicity, change hyperlinked **local personal property office (PPPO)** to **local Transportation Office** to match language at the linked page.
