### ISSUE TITLE
Rewrite of 2nd para of "On the Road" 

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#328]
USTCJ54-PI input  Location: Moving with the Military Overview - What to Expect with a CONUS Move - Rewrite 2nd paragraph of "On the Road" as don't agree with the writing of the paragraph details 

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior - Rewrite to "Depending on whether your household goods will be going into storage or a door-to-door move, will determine what happens next. When the shipment arrives at the destination location, the TSP will attempt to contact you directly to coordinate delivery.  You must be available to confirm delivery within the allowable waiting time (two hours if shipment is moving within the United States or three hours if moved internationally).  It's important that you are available to accept delivery, or your items will be placed into storage."  

_Summarize expected behavior._

## Observed Behavior -  Currently "Depending on whether your household goods will be going into storage or a door-to-door move, will determine what happens next. For those doing a door-to-door, it's important that you arrive before the driver. If the driver arrives at your new residence before you do they may have to put your items in storage, depending on their schedule. For those whose items are going into storage, you have more flexibility with your timing."

_Summarize observed behavior._

## Steps to Reproduce

To reproduce this issue…

1. _  Location: Moving with the Military Overview - What to Expect with a CONUS Move - Rewrite 2nd paragraph of "On the Road"
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[On the Road 2nd para rewrite.pdf](https://github.com/deptofdefense/move.mil/files/1657588/On.the.Road.2nd.para.rewrite.pdf)

**Comment by jillesmith1** [comment]
CLOSE--opinion. The section addresses CONUS moves, not international.
