### ISSUE TITLE
Rewrite 3rd paragraph of "Delivery” about the inventory sheet and loss/damage form

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#329]
USTCJ54-PI input, Located at: Moving with the Military Overview - What to Expect with a CONUS Move - Rewrite 3rd paragraph of "Delivery” inventory sheet and loss/damage form

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior - Rewrite to "Once the truck is empty, you should verify on the inventory sheet that everything has been delivered. If not, those items need to be annotated on the inventory sheet before you sign off. This goes for any damage that may have occurred to the residence.  Additionally, any items not received or which  come in damaged should be annotated on the Notification of Loss/Damage AT Delivery Form provided by the driver.  Don’t worry if you missed something, you have 75 days from the date of delivery to notify the moving company in writing of any loss/damage items which you intend to file a claim for."

_Summarize expected behavior._

## Observed Behavior - Currently "Once the truck is empty, you should verify on the inventory sheet that everything has been delivered. If not, those items need to be annotated on the inventory sheet before you sign off. Additionally, if you saw any items come in damaged, you can annotate that as well, but you'll still have time to file a claim in case you missed it. This goes for any damage that may have occurred to the residence."

_Summarize observed behavior._

## Steps to Reproduce

To reproduce this issue…

1. _  Location: Moving with the Military Overview - What to Expect with a CONUS Move - Rewrite 3rd paragraph of "Delivery” inventory sheet and loss/damage form
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._

[Rewrite 3rd paragraph of   Delivery   inventory sheet and loss damage form.pdf](https://github.com/deptofdefense/move.mil/files/1657658/Rewrite.3rd.paragraph.of.Delivery.inventory.sheet.and.loss.damage.form.pdf)

**Comment by jillesmith1** [comment]
VALID--for dev action.  One note: I recommend changing "annotated" to a common word.

".... those items need to be **written** on the inventory sheet before you sign off.... **Additionally, any missing or damaged items should be written on the Notification of Loss/Damage AT Delivery Form the driver gives you.**..."

**Comment by jgarber623-gov** [comment]
@jdsager @jillesmith1 

It looks like we have similar verbiage in two other places on the site. Do the changes suggested in this issue apply to them as well? For context, here are the two other occurrences:

On [the OCONUS moves page](https://www.move.mil/moving-guide/oconus):

> Once the truck is empty, verify on the inventory sheet that everything has been delivered. If not, those items need to be annotated on the inventory sheet before you sign off. Additionally, if you see any items come in damaged you can annotate that as well, but you’ll still have time to file a claim in case you missed it. This goes for any damage that may have occurred to the residence.

On [the civilians page](https://www.move.mil/moving-guide/civilians):

> Once the truck is empty, verify on the inventory sheet that everything has been delivered. If not, those items need to be annotated on the inventory sheet before you sign off. Additionally, if you see any items come in damaged you can annotate that as well, but you’ll still have time to file a claim in case you missed it. This goes for any damage that may have occurred to the residence.

Let me know if those should change as well and I can quickly make the update.

**Comment by jillesmith1** [comment]
Oh yes, @jgarber623-gov, certainly make/replicate those changes as necessary.

**Comment by jgarber623-gov** [comment]
Thanks, @jillesmith1!
