### ISSUE TITLE
Rewording of "Consumable" 

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#331]
USTC J54-PI input-  Located within... Moving Guide - Entitlements - Special Item Information - Consumable

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior - Rewrite to:  Only allowed for eligible locations
If you are assigned to a permanent duty station  location listed on the JTR, website at, http://www.defensetravel.dod.mil/Docs/AP-CG-01.pdf  you can ship up to 1,250 pounds of suitable consumable goods per each tour year of assignment (i.e. 12-month tour - 1,250 lbs; 18-month tour - 1,875 lbs).
Consumable goods must be packed, marked and weight separately.
Contact your local Personal Property Processing Office (PPPO) for more details

_Summarize expected behavior._

## Observed Behavior - Currently:  Only allowed for **remote** locations.
•If you are assigned to a permanent duty station in a **remote** location listed in the JTR, Appendix F, Part I you can ship up to 1,250 pounds of suitable consumable goods per **a tour** year assignment (i.e. 12-month tour - 1,250 lbs; 18-month tour - 1,875 lbs).
•Consumable goods must be packed, marked and weight separately.
•Contact your local **Personal Property Office (PPPO)** for more details.

_Summarize observed behavior._

## Steps to Reproduce

To reproduce this issue…

1. _  Located within... Moving Guide - Entitlements - Special Item Information - Consumable
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[Consumable  #331.pdf](https://github.com/deptofdefense/move.mil/files/1660251/Consumable.331.pdf)

**Comment by jillesmith1** [comment]
Do we **really** need to post this special entitlement on move.mil?

**Comment by Elliottdotgov** [comment]
This is a question that has come from a least a couple of service members. However, the suggested rewrites are opinions on wording, not facts. This should stay as is.

**Comment by jdsager** [comment]
Jillesmith and Elliottdotgov     If you are leaving this entitlement in ...it needs to be fixed to what the FACT is, it is not an opinion that it's the eligible vs remote... there is a difference in the military of such... also, there is a difference "per a tour year" and "per each tour year" of assignment so they is in the paragraph rewrite also ...why can't the requested changes be made without arguing about them
