### ISSUE TITLE
Correction of "POV (Primary vehicles)" to "POV (Privately Owned Vehicle)"

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#332]
USTC J54-PI input- Located within... Moving Guide - Entitlements - Special Item Information - POV (Primary vehicles) 

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior  Correct subject from "POV (Primary vehicles)" to "POV (Privately Owned Vehicle)"

 Correction to first two bullets...one word and one number (replaced) in each removed ... remove "primary" 1st bullet and replace "1" in 2nd with "your" as more then one can be reimbursed    

Corrected below to read... 

For CONUS:
•The cost of transporting your vehicles to your new PCS is largely your responsibility.
•The military will reimburse you for the mileage associated with driving your POV according to the DOD PCS Mileage Reimbursement rate.

_Summarize expected behavior._

## Observed Behavior Currently subject is   -   POV (Primary vehicles) 
For CONUS:
•The cost of transporting your **primary** vehicles to your new PCS is largely your responsibility.
•The military will reimburse you for the mileage associated with driving **1** POV according to the DOD PCS Mileage Reimbursement rate.

_Summarize observed behavior._

## Steps to Reproduce

To reproduce this issue…

1. _  Located within... Moving Guide - Entitlements - Special Item Information - POV (Primary vehicles) 
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[POV #332.pdf](https://github.com/deptofdefense/move.mil/files/1660327/POV.332.pdf)

**Comment by jillesmith1** [comment]
VALID--for dev action.
