### ISSUE TITLE
Rewording for Motorcycles & Dirtbikes 

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#333]
USTC J54-PI input-  Located within... Moving Guide - Entitlements - Special Item Information - Motorcycles & Dirtbikes .... slight rewording of both paragraphs ... especially change POV from primary to privately own vehicle 

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior -
- For CONUS: Motorcycles/dirt bikes can be shipped as household goods where the weight of the bike is deducted from the total weight of household goods.

- For OCONUS: One motorcycle can be transported as a POV (Privately Owned Vehicle).  Otherwise, motorcycles/dirt bikes can be shipped as household goods where the weight of the bike is deducted from the total weight of household goods. You must look at country requirements prior to shipping a motorcycle to an overseas location to ensure the specific motorcycle is authorized to enter the country

_Summarize expected behavior._

## Observed Behavior  
• One motorcycle can be transported as a POV (Primary Vehicle). Otherwise, motorcycles/dirt bikes can be shipped as a household good where the weight of the bike is deducted from the total weight of household goods.
• For OCONUS: You must look at country requirements prior to shipping a motorcycle to an overseas location to ensure the specific motorcycle is authorized to enter the country.

_Summarize observed behavior._

## Steps to Reproduce

To reproduce this issue…

1. _  Located within... Moving Guide - Entitlements - Special Item Information - Motorcycles & Dirtbikes
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[Motorcycles & Dirtbikes   #333.pdf](https://github.com/deptofdefense/move.mil/files/1660416/Motorcycles.Dirtbikes.333.pdf)

**Comment by jillesmith1** [comment]
VALID--for dev action.
1. Re-write first bullet to read, "For CONUS: Motorcycles and dirt bikes can be shipped as household goods. That weight is deducted from your total household goods weight."

2.  Re-write second bullet to read, "For OCONUS: One motorcycle can be transported as a POV (privately owned vehicle). If you ship your motorcycle or dirt bike as household goods, the weight is included in your total household goods weight." 

3.  Create third bullet, bolded, to read, "**Check the country requirements before you ship your motorcycle or dirt bike overseas!** There may be import restrictions or prohibitions for bringing your specific motorcycle or dirt bike into the country you’re moving to. Contact your local personal property office if you have questions."
