### ISSUE TITLE
Spare POV (Primary Vehicle) Parts paragraphs rewrite 

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#334]
USTC J54-PI input-  Located within... Moving Guide - Entitlements - Special Item Information - Spare POV Parts 

## Checklist

I have…

- [ ] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [ ] attached screenshots illustrating relevant behavior.

## Expected Behavior - Rewrite to ...
- The weight of any spare POV (Privately Owned Vehicle) parts will be deducted from the total allowed weight of household goods.
- Examples of POV parts might include car engine, transmission, including integral/attached vehicle parts (e.g., seats, tops, winch, spare tires, portable gas cans, GPS systems and CD players) or other items with a high vulnerability of pilferage

_Summarize expected behavior._

## Observed Behavior - currently... 
•The weight of any spare **POV (Primary Vehicle)** parts will be deducted from the total allowed weight of household goods.
•Examples of POV parts might include car engine, transmission, seats, tops, winch, spare tires, portable gas cans, GPS systems and CD players or other items with a high vulnerability of pilferage.

_Summarize observed behavior._

## Steps to Reproduce

To reproduce this issue…

1. _  Located within... Moving Guide - Entitlements - Special Item Information - Spare POV Parts 
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[Spare POV parts # 334.pdf](https://github.com/deptofdefense/move.mil/files/1660507/Spare.POV.parts.334.pdf)

**Comment by jillesmith1** [comment]
VALID--for dev action. 
1.  Re-write first bullet to read, "The weight of any spare POV parts will be deducted from the total allowed weight of household goods." 
2.  Re-write second bullet to read, "Examples of spare POV parts might include a car engine, transmission, seats, tops, winch, spare tires, portable gas cans, GPS systems, CD players, and other items that could be misplaced or stolen."
