### ISSUE TITLE
Boat or Personal Watercraft (Not primary residence) 3rd bullet, remove 2nd to last sentence 

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#335]
USTC J54-PI input-  Located within... Moving Guide - Entitlements - Special Item Information - Boat or Personal Watercraft (Not primary residence .... Just requesting this last sentence be removed, the rest can go through the PPPO as suggested…  “If you can figure out how to move your boat for less money than the government pays your, than you can keep the rest" 

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior .... within third bullet down... requesting to have 2nd to last sentence removed ..remove "If you can figure out how to move your boat for less money than the government pays your, than you can keep the rest"

•It is highly suggested, that you consider doing a Personally Procured Move (PPM) for your boat. In this option, the government will either pay you to move your boat or you have the ability to select your own commercial boat hauler. **If you can figure out how to move your boat for less money than the government pays your, than you can keep the rest**. How much money will the government pay me to move my boat?

_Summarize expected behavior._

## Observed Behavior- currently...  •It is highly suggested, that you consider doing a Personally Procured Move (PPM) for your boat. In this option, the government will either pay you to move your boat or you have the ability to select your own commercial boat hauler. If you can figure out how to move your boat for less money than the government pays your, than you can keep the rest. How much money will the government pay me to move my boat?

_Summarize observed behavior._

## Steps to Reproduce

To reproduce this issue…

1. _  Located within... Moving Guide - Entitlements - Special Item Information - Boat or Personal Watercraft (Not primary residence .... 
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[Boat or Personal Watercraft one sentence removal  #335.pdf](https://github.com/deptofdefense/move.mil/files/1660637/Boat.or.Personal.Watercraft.one.sentence.removal.335.pdf)

**Comment by jillesmith1** [comment]
VALID--for dev action. Re-write the third bullet, third sentence to read, "It is highly suggested that you consider doing a Personally Procured Move (PPM) for your boat. In this option, the government will either pay you to move your boat or you have the ability to select your own commercial boat hauler. <How much money will the government pay me to move my boat?>"
