### ISSUE TITLE
OCONUS Packing Day 

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#336]
Moving Guide - Overseas Moves (OCONUS) - What to Expect with an OCONUS (Overseas) Move - Packing Day

## Checklist

I have…

- [ ] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [ ] attached screenshots illustrating relevant behavior.

## Expected Behavior  Rewrite paragraph to following as two sentence have been rewritten "Your packing day and moving dates are not the same thing. On packing day, the moving company sends a team of packers to your home to prepare furniture items, as well as pack items into boxes. The day your furniture and boxes are loaded into overseas containers or onto the truck could be several days later."

Next paragraph just need PPPO at the end fixed 

The packers are supposed to call ahead of time to inform you they will be coming out on certain dates and within a specified time period. It's critical that you're available during this time. If for some reason the Moving Company fails to show, quickly notify your local personal property office (PPPO).

_Summarize expected behavior._ Throughout Move.mil, can we get PPPO corrected to Personal Property Processing Office ... most reference have "local personal property office (PPPO)"

## Observed Behavior
Packing Day
Your packing day and moving dates are not the same thing. On packing day, the moving company sends a team of packers to your home and puts all your items into boxes, usually as fast as possible. The day your **boxed** are loaded onto the truck for moving day could be several days later.

The packers are supposed to call ahead of time to inform you they will be coming out on certain dates and within a specified time period. It's critical that you're available during this time. If for some reason the Moving Company fails to show, quickly notify your **local personal property office (PPPO).**

_Summarize observed behavior._

## Steps to Reproduce

To reproduce this issue…

1.   Moving Guide - Overseas Moves (OCONUS) - What to Expect with an OCONUS (Overseas) Move - Packing Day
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[OCONUS Packing Day #336.pdf](https://github.com/deptofdefense/move.mil/files/1660704/OCONUS.Packing.Day.336.pdf)

**Comment by jillesmith1** [comment]
VALID--for dev action. 
1.  Change Packing Day first paragraph to read, "Your packing day and moving dates are not the same thing. On packing day, the moving company sends a team of packers to your home and puts all your items into boxes, usually as fast as possible. The day your boxes are loaded onto the truck for moving day could be several days later."

No action required on the second part--customers use the term personal property office versus the formal government naming convention.

**Comment by jgarber623-gov** [comment]
@jillesmith1 A similar paragraph appears on [the civilians moving page](https://www.move.mil/moving-guide/civilians). Should that be updated as well?

**Comment by jillesmith1** [comment]
Yes, @jgarber623-gov. Thank you.

**Comment by jgarber623-gov** [comment]
@jillesmith1 Oh, hah! Never mind. The civilians copy matches the change requested in this issue.
