### ISSUE TITLE
Lackland AFB Locator update 

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#337]
Lackland locator, along with FORT SAM HOUSTON and RANDOLPH AFB needs updated as below 

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior - Change the Physical Location of Lackland to:

1561 Stewart Street
Bldg. 1516
JBSA Lackland AFB, TX 78236

Mailing Address: 502 LRS/LGRDF, 1865 Selfridge Avenue, JBSA Lackland AFB, San Antonio, TX 78236

Please add the following:

Hours:
-Mon-Tues-Thurs-Fri 0700-1600
-Closed Wed 1400 for AETC mandatory training, Weekends, Holidays, & AETC Family Days

Notes:
-PPM Mass Briefings during peak season (June-Aug) by appt. only -Mon-Wed-Fri @ 1000 Student Mass Briefings 

Services:
- Walk-In Help
- Briefings
- Appointments

Also for location:  FORT SAM HOUSTON
Physical Location: 2484 Stanley Rd, Bldg. 2263, JBSA Ft Sam Houston
San Antonio, TX 78234

FORT SAM HOUSTON Mailing Address:  502 LRS/LGRDF, 1865 Selfridge Avenue, JBSA Lackland AFB, San 
Antonio, TX 78236

Also for location: RANDOLPH AFB
Physical Location: 555 D St East, Bldg. 399, JBSA Randolph AFB
Universal City, TX 78148

RANDOLPH AFB Mailing Address:  502 LRS/LGRDF, 1865 Selfridge Avenue, JBSA Lackland AFB, San 
Antonio, TX 78236

_Summarize expected behavior._  Please add to the Lackland AFB locator ...attached example of how the Fort Sam Houston is right below it so it looks like all being asked for is available to be entered 

## Observed Behavior - Lackland AFB missing information - See attached as it shows the area missing compared to the next one down, Fort Sam Houston 

_Summarize observed behavior._

## Steps to Reproduce

To reproduce this issue…

1. _ Enter "Lackland" into the locator and it should be the first thing that populates ...Also need to update FORT SAM HOUSTON and RANDOLPH AFB with physical and mailing addresses. 

1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[Lackland Locator update  GitHub #337.pdf](https://github.com/deptofdefense/move.mil/files/1661176/Lackland.Locator.update.GitHub.337.pdf)

**Comment by jillesmith1** [comment]
VALID--for dev action.
