### ISSUE TITLE
Marine retirees/separatees Advance Payment for PPM change from 60% to 50 

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#339]
Marines only allowed 50%, only thing to change from 60 to 50% in sentence 

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior-  Marines: Marine retirees and separatees can receive an advancement of up to 50% of the 95% PPM incentive payment

_Summarize expected behavior._

## Observed Behavior - Marines: Marine retirees and separatees can receive an advancement of up to 60% of the 95% PPM incentive payment

_Summarize observed behavior._

## Steps to Reproduce

To reproduce this issue…

1. _ Located at Moving Guide – Retirees/Separatees - Retiree and Separatee Moves - : Advance Payment for PPM “Do-it-Yourself” Moves
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[Advance PPM for Marine #339.pdf](https://github.com/deptofdefense/move.mil/files/1664748/Advance.PPM.for.Marine.339.pdf)

**Comment by jillesmith1** [comment]
VALID--for dev action.
