### ISSUE TITLE
Tutorials - Create a Shipment - Slide 9 Orders Information explain 3rd fill area 

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#341]
Under Orders information for Create a Shipment Slide 9 - Blocks one and two are explained in the tutorial however block three is a mandatory entry field and also requires tutorial assistance.  Block three is the Headquarters Issuing Orders (who cut/issued the orders) which is located on the orders.  Location may vary for each individual service  

## Checklist

I have…

- [ ] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [ ] attached screenshots illustrating relevant behavior.

## Expected Behavior -  On Slide 9 where it has "INSTRUCTIONS Next, enter your Orders Number and Date.  Change to "INSTRUCTIONS Next, enter your Orders Number, Date and the Headquarters Issuing the Orders"

Within Pro-Tips 1st bullet of this slide...within last sentence fix "Airforce" to "Air Force"

_Summarize expected behavior._

## Observed Behavior -  There's three blocks in this area at highlighted on the attached and the third is not addressed  "INSTRUCTIONS Next, enter your Orders Number and Date."  

Within Pro-Tips 1st bullet of this slide...within last sentence ..."For the Airforce, look in box 27 of your Orders form" ...fix "Airforce" to "Air Force"

_Summarize observed behavior._

## Steps to Reproduce

To reproduce this issue…

1. _  Located within: Tutorials - Create a Shipment - Slide 9 which is Orders Information 
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._

[Orders are of Create a Shipment Slide 9 fix Air Force also #341.pdf](https://github.com/deptofdefense/move.mil/files/1665533/Orders.are.of.Create.a.Shipment.Slide.9.fix.Air.Force.also.341.pdf)

**Comment by jillesmith1** [comment]
VALID--for dev action. In Pro-Tips, bullet one, sentence three, re-write, "For the Air Force, look in box 27..."

**Comment by jgarber623-gov** [comment]
Resolved by #375. 🏆
