### ISSUE TITLE
Create a Shipment Slide #14 Pro-Tip POV rewrite from Personally Owned Vehicle 

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#342]
Pro-Tips A - POV is your Privately Owned Vehicle , and in this context, a Mobile Home is an RV

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior - "Pro-Tips - A POV is your Privately Owned Vehicle"  remove  "and in this context, a Mobile Home is an RV"

_Summarize expected behavior._

## Observed Behavior - Currently 1st bullet of Pro-Tips "- A POV is your Personally Owned Vehicle, and in this context, a Mobile Home is an RV" 

_Summarize observed behavior._

## Steps to Reproduce

To reproduce this issue…

1. _  Located within "Tutorials - Create a Shipment - Slide #14 Pro-Tip ...
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[Create a Shipment Pro-Tip Slide 14 POV correction #342.pdf](https://github.com/deptofdefense/move.mil/files/1665854/Create.a.Shipment.Pro-Tip.Slide.14.POV.correction.342.pdf)

**Comment by jillesmith1** [comment]
VALID--for dev action. Change first Pro-Tip bullet to read, "A POV is your privately owned vehicle or automobile. Contact you local Transportation Office if you have questions."

**Comment by Elliottdotgov** [comment]
We heard this from a number of Service Members. Unless this is incorrect information we should keep it.

**Comment by jillesmith1** [comment]
Concur. Re-write to read, "A POV is your privately owned vehicle or automobile and in this context, a Mobile Home is an RV or recreational vehicle. Please contact your local Transportation Office if you have questions."

**Comment by jgarber623-gov** [comment]
Resolved by PR #373.
