### ISSUE TITLE
Remove "Spouse information" being entered in "Additional Information" that refers to articles being shipped and rewrite Pro-Tip Slide #17

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#343]
We have no rules to include Dual Mil spouse information into “Additional Information” block. Need to remove that and see rewrite of 2nd bullet on same slide of the Pro-Tips

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior- Under INSTRUCTIONS ...remove lines 3-8.. starting third sentence "Enter your spouse's infor......and ending with ...Total Estimate Weight of the Shipment"

Under same Slide #17, 2nd bullet under Pro-Tips, Rewrite to "Within the next section, you will enter firearms required information pertaining to being shipped within the household goods" 

Summarize expected behavior._

## Observed Behavior - As identified on attached, remove Spouse information and rewrite 2nd bullet of Pro-Tips pertaining to firearms. 

_Summarize observed behavior._

## Steps to Reproduce

To reproduce this issue…

1. _ Located at: Tutorial - Dual Military (Mil-to-Mil) Move...Side 17 of 23 
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[Dual Mil Est Wt  #343.pdf](https://github.com/deptofdefense/move.mil/files/1665933/Dual.Mil.Est.Wt.343.pdf)

**Comment by jillesmith1** [comment]
VALID--for dev action. 
     1.  Remove all text under slide 17 of 23, "Enter your spouse's information here.... Total Estimate Weight of the Shipment."
     2.  Pro-Tips, second bullet, second sentence re-write to read, "You'll need to enter the make a model, serial number, and caliber for each firearm."

**Comment by jillesmith1** [comment]
Typo noted in the text... sent correction as "You'll need to enter the make, model, serial number, and caliber for each firearm."
