### ISSUE TITLE
FAQ "What happens if our shipment went over our weight limit?"

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#349]
Frequently Asked Questions - 8th FAQ within "After The Move"- "What happens if our shipment went over our weight limit?"

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior Rewrite paragraph for better understanding to  "If you receive an email notification from the shipping system (DPS), or other notification from personal property personnel, that you went over the authorized weight limit, there are several things you should do:  (1) double check to ensure all professional gear (both the member and spouse) as indicated on the inventory forms was removed from the total net weight being shipped, and (2) you should be removing the weight of the “packing material” (usually 10% of net) from that total net weight also...Then (3) if you are still exceeding your authorized weight, request a reweigh to be accomplished before delivery. If after all this you are still overweight, expect to pay back the excess shipping cost when contacted by Service Excess Cost Center. "

_Summarize expected behavior._

## Observed Behavior - currently the paragraph is mis-leading as you won't get notified to reimburse the govt until way after delivery is made and it's to late to be asking for a reweigh then.  - As written... "If you receive notification from the property office that you went over the weight limit and have to reimburse the government, the two things you should do first is double check to ensure all professional gear (both the member and spouse) was removed from the total weight and then you can request a re-weight of the items. They should also be removing “packing material” from the total as well… this includes all the boxes and paper needed to pack your HHGs. If after all this you are still overweight, expect to pay back the overage amount."

_Summarize observed behavior._

## Steps to Reproduce

To reproduce this issue…

1. _Describe step one._
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[If over weight rewrite  #349.pdf](https://github.com/deptofdefense/move.mil/files/1669063/If.over.weight.rewrite.349.pdf)

**Comment by jillesmith1** [comment]
VALID--for dev action. Re-write to "If you receive notification from the shipping system (DPS) or the personal property office that you went over your authorized weight limit, there are a few things you can do. First, check to see if the weight of all professional gear (yours and your spouse's) listed on your inventory form was subtracted from the total net weight you shipped. Second, subtract the weight of the “packing material” (usually 10% of the net weight) from that total net weight. If you are still over your authorized weight and your shipment has NOT been delivered to you yet, you can request a reweigh before your household goods are brought to your new home. If the reweigh shows you're **_**still**_** over your allowance, expect to pay back the excess shipping costs. You can also contact your local personal property office for assistance.
