### ISSUE TITLE
PPPO update for Customer Service and Locator 

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#351]
ALL of the references to PPPO should be the Personal Property Processing Office ...not TO or local personal property office ... see attachments 

## Checklist

I have…

- [ ] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [ ] attached screenshots illustrating relevant behavior.

## Expected Behavior -  ALL of the references/acronym for PPPO should be the Personal Property Processing Office ...not TO or local personal property office ... examples of errors in attached 

_Summarize expected behavior._  

## Observed Behavior - Most of the move.mil site has PPPO as the local personal property office, just need to get it to the correct thing 

_Summarize observed behavior._

## Steps to Reproduce

To reproduce this issue…

1. _ Customer Service and Locator areas identified in attached 
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._ 
[PPPO update throughout 351.pdf](https://github.com/deptofdefense/move.mil/files/1669175/PPPO.update.throughout.351.pdf)

[PPPO updates in Move mil 351.pdf](https://github.com/deptofdefense/move.mil/files/1669158/PPPO.updates.in.Move.mil.351.pdf)

**Comment by jillesmith1** [comment]
CLOSE. IAW design principles and plain-language simplicity, customers recognize the term "personal property office."
