### ISSUE TITLE
Adding Consignment Guide Instructions 

### ISSUE THREAD

**Issue by robert078** [deptofdefense/move.mil#357]
Country instructions are needed by other non-DPS users, as well as service members who are PCSing in order to see specific country instructions and locations pertaining to their move. Redesign of the user roles won't allow customers to access these instructions, and the issue with Apache Struts have disabled anyone from viewing the consignment guide by other means. The following two PDF files need to be uploaded so that these instructions can be made available to DPS users. 

Personal Property Consignment Instructions Guide (PPCIG)
The Personal Property Consignment Instruction Guide – Manage the Consignment Instruction Guide process for the Department of Defense (DoD) transportation community.  

Conus Consignment Guide   (link to PDF)         Oconus Consignment Guide – (link to PDF) / Coming Soon 

Country Instructions (link to PDF)

[DPS consignGuideConus.pdf](https://github.com/deptofdefense/move.mil/files/1711850/DPS.consignGuideConus.pdf)
[PPCIG Country Instructions 10 Jan 2018.pdf](https://github.com/deptofdefense/move.mil/files/1711852/PPCIG.Country.Instructions.10.Jan.2018.pdf)

**Comment by jillesmith1** [comment]
Team, 
"... a PDF of the current PPCIG should not go on Move.mil. The site was designed to replace lengthy PDFs like the PPCIG with mobile-friendly, user-tested plain-language written webpages. And based on the feedback [DDS has] received thus far from staff with direct customer engagement roles (PPPOs) as well as Service Members themselves, there haven't been any significant or glaring omissions on Move.mil of things covered by the PPCIG. 

"I know to some of the SMEs within USTRANSCOM this may feel like a backwards way of doing things, but the driving principle behind content and feature development on move.mil is that it is all user-driven. That means reducing the information presented to the very minimum to catch the 80% of cases, most frequently asked questions, and the like. Now if there are compelling sources of user data we may have missed (like SRC call data with common questions) we are all for incorporating that as a form of user need. But aside from the SRC, USTC is not at the forefront of direct customer engagement so for the purposes of move.mil development, users, data about users, and data from those who directly support users are the main categories of new info/features.

"If there are things you think we missed and you have some user data to back it up, send it over to the shared org mailbox at J4-H [army.sddc.safb.ppops@mail.mil] and we'll review it as part of the prioritization exercise for the content strategy and kickoff meeting with Bixal."
