### ISSUE TITLE
Service Level User Restrictions 

### ISSUE THREAD

**Issue by robert078** [deptofdefense/move.mil#358]
Need to add the restrictions for counseling in DPS for customers that need to be added to move.mil. DPS Customers may NOT be able to use DPS to perform self-counseling depending upon the type of personal property move and the Service the customers are in. Below are the Service guidelines by branch.

USA

If this is your first personal property move.
If this is your last personal property move (retirement or separation).
If you are storing or moving personal property in conjunction with contingency orders.
If you are storing or moving personal property in conjunction with a designated location for your dependents to an OCONUS or Non-foreign OCONUS location.
If you are not the property owner and using a Power of Attorney.
If you are moving personal property as "next of kin" or are a Summary Courts Officer.

USMC

Personnel using a Power of Attorney or are "next of kin" are REQUIRED to contact their local Personal Property Office before self-counseling using DPS. All other personnel listed below ARE HIGHLY ENCOURAGED to contact the local Personal Property Office before self-counseling to receive additional,
targeted counseling: 
If this is your first personal property move.
If this is your last personal property move (retirement or separation).
If you are storing or moving personal property in conjunction with contingency orders.
If you are storing or moving personal property in conjunction with a designated location for your dependents to an OCONUS or Non-foreign OCONUS location.
If you are not the property owner and using a Power of Attorney.

USN

If you are moving personal property as "next of kin" or are a Summary Courts Officer.

USAF

If this is your first personal property move.
If this is your last personal property move (retirement or separation).
If you are not the property owner and using a Power of Attorney.
If you are moving personal property as "next of kin" or are a Summary Courts Officer.

USCG

If this is your first personal property move.
If this is your last personal property move (retirement or separation).
If you are not the property owner and using a Power of Attorney.
If you are moving personal property as "next of kin" or are a Summary Courts Officer.

**Comment by jgarber623-gov** [comment]
☝️  Tagging @lfantano and @LillyMadigan on this one. See @jillesmith1's question:

> Designers, where should this information be posted? Under "Plan Your Move" or another spot?

**Comment by lfantano** [comment]
@jgarber623-gov  Let's do this: 

Let's create a new FAQ question on the FAQ page called, "Can I use the online move scheduling system (DPS) to schedule my move?" Then put the answer text by branch of service in the reply. For each branch of service, can you incorporate bullets so it looks more like a list?

On the home page, "Schedule Your Move" section, lets change "Sign In to DPS to schedule your move online" to "Sign In to DPS to schedule your move online (Find out if I am allowed to use DPS to schedule my upcoming move.)" 

The text in the () can link to the FAQ and anchor to that specific question.
