### ISSUE TITLE
Locator Map change for Lackland AFB, TX

### ISSUE THREAD

**Issue by humlah** [deptofdefense/move.mil#359]
Need the location/address updated for the PPPO Office at Lackland AFB, TX

Location needs to read:
1651 Stewart Street
Bldg: 5616
JBSA Lackland AFB
San Antonio, TX 78236

move.mil is currently displaying the Wrong Bldg of 1516.
All other information is good.
[Lackland location.docx](https://github.com/deptofdefense/move.mil/files/1725598/Lackland.location.docx)

**Comment by jillesmith1** [comment]
VALID--for dev action.
