### ISSUE TITLE
Add missing weighing locations under Hurlburt AFB, FL 32544

### ISSUE THREAD

**Issue by humlah** [deptofdefense/move.mil#360]
Current  move. mil locator map does not show Weighing locations under the PPPO Hurlbert AFB, FL
current screen shot of move.,mil has been provided.

We have provide the attached document to add the missing three (3) weighing locations to be inserted between the Hurlburt AFB and the Eglin AFB PPPO location data.
[Current Locator Map for Hurlburt AFB, FL.docx](https://github.com/deptofdefense/move.mil/files/1725719/Current.Locator.Map.for.Hurlburt.AFB.FL.docx)
[move.mil to show (NEW) Hurlburt AFB weighing locations.docx](https://github.com/deptofdefense/move.mil/files/1725721/move.mil.to.show.NEW.Hurlburt.AFB.weighing.locations.docx)

**Comment by jillesmith1** [comment]
VALID--for dev action.
