### ISSUE TITLE
Asia Claims office requested changes

### ISSUE THREAD

**Issue by humlah** [deptofdefense/move.mil#364]
Mr Feist, U.S. Army Claims Service, Asia submitted requested changes to current information posted on the move.mil webiste

## Checklist

I have…

- [x ] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x ] attached screenshots illustrating relevant behavior.

## Expected Behavior
The current displayed information on the Service-Specific Information page for ARMY under Customer Service Info Claims for the Asia (Korea and Japan) needs to be replaced. 
_Summarize expected behavior._

## Observed Behavior
Current information is: Email: | usarmy.yongsan.8-army.mbx.osja-client-legal-services@mail.mil
 Address: US Armed Forces Claims Service - Korea            
 ATTN: Military Claims Division; Unit 15311             
APO AP 96205-5311

NEW Information to show: 
Email: usarmy.humphreys.8-army.mbx.osja-client-legal-services
Address:   U.S. Army Claims Service Asia
                Office of the SJA, Eighth Army
                Unit 15236
                APO 96271-5236
Commerical: +82-50-3357-2607/2631/2632
DSN: 315-757-2607/2631/2632

_Summarize observed behavior._

## Steps to Reproduce

To reproduce this issue…

1. _Describe step one._
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots
screen shot of current displayed information and required changes.
[Asia Claims information update.docx](https://github.com/deptofdefense/move.mil/files/1759554/Asia.Claims.information.update.docx)

_Attach relevant screenshots here._

**Comment by jillesmith1** [comment]
VALID--for dev action.
