### ISSUE TITLE
Changes to Retirees/Separatees under Moving Guide

### ISSUE THREAD

**Issue by humlah** [deptofdefense/move.mil#370]
US Air Force Personal Property Activity (PPA) requested the following update to the Retirees/Separatees information under Moving Guide tab on Move.Mil website.
## Checklist

I have…

- [x ] described in detail below both the behavior I expected and the behavior I observed.
- [ x] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [ x] attached screenshots illustrating relevant behavior.

## Expected Behavior

_Summarize expected behavior.
Change the following to read 
For retirees or separatees with more than 8 years of continuous active duty: The government will cover the cost of relocating you to your Home of Selection (HOS), anywhere within the United States.  This is only the case for Separatees when they receive severance or separation pay per JTR 052013-A1c and there is no break in service of 91 days or more.  

You can still move outside the United States, however you will be responsible for any additional costs above what it would have cost to move you within the contiguous 48-states. To determine the government cost, the Personal Property Office typically uses the cost of transporting your entire weight allowance to the farthest possible location within the 48-contiguous states from your current station to calculate the government's maximum liability

   

## Observed Behavior

_Summarize observed behavior.
Move.mil currently reads:
 For retirees or separatees with more than 8 years of continuous active duty: The government will cover the cost of relocating you to your Home of Selection (HOS), anywhere within the United States.

You can still move outside the United States, however you will be responsible for any additional costs above what it would have cost to move you within the contiguous 48-states. To determine the government cost, the Personal Property Office typically uses the cost of transporting your entire weight allowance to the farthest possible location within the 48-contiguous states from your current station to calculate the government's maximum liability 

## Steps to Reproduce

To reproduce this issue…

1. _Describe step one._
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant
[Move.mil updates to Retirees _ Separatees information.docx](https://github.com/deptofdefense/move.mil/files/1804299/Move.mil.updates.to.Retirees._.Separatees.information.docx)
 screenshots here._

**Comment by jillesmith1** [comment]
Reopened. For developer action: needs a text change to: "**For retirees or separatees with more than 8 years of continuous active duty**: The government **may** cover the cost of relocating you to your Home of Selection (HOS), anywhere within the United States, depending upon your type of discharge. Contact your local personal property office for more information."
Received email from Joint Base San Antonio-Randolph, TX. Requestor notified J4 that two customers challenged an entitlement posted on Move.mil, "Retiree and Separatee Moves" (https://www.move.mil/moving-guide/retirees-separatees).
