### ISSUE TITLE
Marine Corps Logo

### ISSUE THREAD

**Issue by humlah** [deptofdefense/move.mil#371]
US Marine Corps HQ is requesting the attached Logo be placed on the move.mil website 

## Checklist

I have…

- [ ] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [ ] attached screenshots illustrating relevant behavior.

## Expected Behavior

_Summarize expected behavior._

## Observed Behavior

_Summarize observed behavior._

## Steps to Reproduce

To reproduce this issue…

1. _Describe step one._
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screensh
![marine corps i l logo](https://user-images.githubusercontent.com/36166691/37306299-41a99bb4-2605-11e8-9a05-646445f535aa.gif)
ots here._

**Comment by jgarber623-gov** [comment]
@humlah Could you provide more details on this request? There's no clear indication as to where on the website USMC would like this graphic.

**Comment by robert078** [comment]
At the top, like the other services have.

See below for example

![graphic example](https://user-images.githubusercontent.com/36198616/37835829-140e6310-2e7f-11e8-8cba-d7a7362e3f96.PNG)

**Comment by pglevy** [comment]
@jillesmith1, We should avoid using animated images, particularly as page banners. Also, the image appears to be distorted and low quality resolution. Is there an alternative image we can use here?

**Comment by robert078** [comment]
Is this image better?


![flag_of_the_united_states_marine_corps_svg](https://user-images.githubusercontent.com/36198616/38334024-d947bc9a-381f-11e8-9cd8-564dbbe45102.png)

**Comment by jamesatheyDDS** [comment]
In keeping with the style used for the Army and Air Force, what does everyone think of this mockup?
![marines-mockup](https://user-images.githubusercontent.com/26554826/38429417-48eae122-398c-11e8-950d-2eac72e1c35d.jpg)

[The photo in the background was published on marines.mil and is Public Domain.](http://www.marines.mil/Photos/igphoto/2001881209/)

**Comment by jamesatheyDDS** [comment]
Here's a different version, with a different balance and crop of the background photo:
![marines-mockup2](https://user-images.githubusercontent.com/26554826/38429676-15797f1e-398d-11e8-935a-9f8e46a68cf6.jpg)
