### ISSUE TITLE
Numeric only keyboard (0-9) input for form fields with input type number (on iphone/mobile browsers)

### ISSUE THREAD

**Issue by schustdj** [deptofdefense/move.mil#374]
Thanks for submitting an issue! Below are a few things you can do to help us more quickly address the issue.

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [x] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior

When a user puts the focus on a form field whose expected input is a number, the numeric dial pad (0-9) style keyboard should appear to accept user input. Its faster, easier.

## Observed Behavior

When a user puts focus on a form field whose expected input is a number, the **full qwerty-style keyboard appears,** requiring the user to first toggle to the numeric and symbol input keyboard, and then utilize the top row of numbers 0-9 to enter values into the fields. 

## Steps to Reproduce

To reproduce this issue…

1. Open https://www.move.mil/ in Safari on iPhone running iOS 11.2.6
2. Navigate to Menu -> Tools & Resources -> PPM Estimator (Or Weight Estimator)
3. Put focus on any field requesting numeric input ("Where are you moving from and to?", Origin Zip Code)

Note: Not tested on Android. Let me know if I left anything out. I also have some other input validation improvements, but just wanted to see if this was possible to do before adding other things onto the issues list.

## Screenshots

<img width="1163" alt="qwerty keyboard screenshot" src="https://user-images.githubusercontent.com/35304127/37374129-9def422e-26e7-11e8-9dfe-823a10e264a4.png">

**Comment by jgarber623-gov** [comment]
Based on the conversation in standup today, assigning this one to @jamesatheyDDS for additional insight.
