### ISSUE TITLE
Add second google analytics tag for team members without .mil addresses

### ISSUE THREAD

**Issue by rich-allen-gov** [deptofdefense/move.mil#377]
- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [ ] attached screenshots illustrating relevant behavior.

## Expected Behavior
The design and dev team would like to have easy access to google analytics regardless of having a .mil address. After chat over slack it was decided it was desirable to have a second google analytic tracking id added to the site.

**Comment by pglevy** [comment]
@rich-allen-gov , this appears to be done. is it time to close out this issue?
