### ISSUE TITLE
Vessel Manifest Confidentiality Request Form (Opt Out Form)

### ISSUE THREAD

**Issue by robert078** [deptofdefense/move.mil#379]
This form needs to be added to the site for customers who want to keep their information confidential during import/export of their household goods and personal affects. 

- [X ] attached screenshots illustrating relevant behavior.

[Confidentiality Request Form Final as of 4 Aug 16.pdf](https://github.com/deptofdefense/move.mil/files/1819332/Confidentiality.Request.Form.Final.as.of.4.Aug.16.pdf)

**Comment by jillesmith1** [comment]
VALID--for design review and action.

**Comment by jgarber623-gov** [comment]
There are some problems with this issue:

1. The attached PDF contains only the following text:

<img width="488" alt="screen shot 2018-03-16 at 12 02 17 pm" src="https://user-images.githubusercontent.com/27780860/37531235-f20becd2-2911-11e8-92f3-90bfcb751fe1.png">

2. This issue lacks information about where on the site we should include this PDF.

@jillesmith1 @robert078 Could one or both of you provide additional details?

**Comment by robert078** [comment]
1. Cannot open the screenshot for some reason in two different browsers, is there a specific comment or question you have with the form? I checked the attachment and the PDF does open correctly in the above issue location. 

2. That's a good question, from my perspective, I had thought tools and resources tab. That's just my two cents, but it has to be consistent with standing guidance and design development thus far and I digress to those smarter than I.

**Comment by jgarber623-gov** [comment]
@robert078 The file attached to the original issue is not a form. It's a PDF with some text in it about upgrading Adobe Reader:

```
Please wait...

If this message is not eventually replaced by the proper contents of the document, your PDF viewer may not be able to display this type of document.

You can upgrade to the latest version of Adobe Reader for Windows®, Mac, or Linux® by visiting http://www.adobe.com/go/reader_download.

For more assistance with Adobe Reader visit http://www.adobe.com/go/acrreader.

Windows is either a registered trademark or a trademark of Microsoft Corporation in the United States and/or other countries. Mac is a trademark of Apple Inc., registered in the United States and other countries. Linux is the registered trademark of Linus Torvalds in the U.S. and other countries.
```

**Comment by robert078** [comment]
@jgarber623-gov  yea guess that isn't gonna work for you. How about this one?

[Confidentiality Request Form Final as of 4 Aug 16.pdf](https://github.com/deptofdefense/move.mil/files/1820359/Confidentiality.Request.Form.Final.as.of.4.Aug.16.pdf)

**Comment by jgarber623-gov** [comment]
@robert078 Looks to be the same. Any chance this form is already online at a URL you can point me to (instead of uploading an attachment to this issue)?

**Comment by robert078** [comment]
@jgarber623-gov  heres a link

https://archive.move.mil/documents/Confidentiality%20Request%20Form.pdf

**Comment by jgarber623-gov** [comment]
Thanks, @robert078!

Looks like this PDF uses some advanced Adobe-specific PDF features. It works in Adobe Acrobat Reader DC, but not in macOS' Preview app.

**Comment by robert078** [comment]
@jgarber623-gov  not a problem, yea I just seen it was DC, least you can see it now.
