### ISSUE TITLE
Add PPO Great Lakes to locator map 

### ISSUE THREAD

**Issue by robert078** [deptofdefense/move.mil#380]
Naval Training center PPO  
1710 B Cavin Dr, BLDG 8100
Great Lakes, IL 60088
Serviced by JPPSO NE
Phone number 1-800-637-5401
DSN 792-5371
customer service email HHG_GreatLakes@navy.mil
Hours of operation 0730-1630   Mon-Fri
Lat  42.303864 
Long  -87.862318

**Comment by jillesmith1** [comment]
VALID--for dev action.
