### ISSUE TITLE
Remove verbiage to moving guide (PPM OCONUS)

### ISSUE THREAD

**Issue by robert078** [deptofdefense/move.mil#386]
Please remove the below verbiage from the following location:  Moving Guide > Moving with the Military Overview > Move Types > Personally Procured Move (PPM):

Verbiage to be removed 
*PPMs for OCONUS Permanent Change of Duty Station Moves are generally reserved for situations where the government does not have the resources to arrange a household goods move. These moves are reimbursed at 100% of the actual cost

Also please revise the following (in the same location):
Did You Know: If the government cannot arrange a Household Goods (HHG) move within the time frame requested, you can do a PPM and receive reimbursement up to the cost the government would pay to have the same weight moved. Please see your Personal Property office to find out more about PPM moves.

The following screenshot is the verbiage to be removed
![ppm oconus](https://user-images.githubusercontent.com/36198616/37738337-b13950fc-2d24-11e8-8bdc-ba076b2a926d.PNG)

**Comment by jamesatheyDDS** [comment]
@robert078 Can you clarify what is accurate or inaccurate about the language that's currently there?

**Comment by jillesmith1** [comment]
No action required--closed. This information reflects SvcHQs/PPSO perspectives on OCONUS PPMs. Both data points shall be retained on the site.
