### ISSUE TITLE
Update Moving guide (Consumable Items)

### ISSUE THREAD

**Issue by robert078** [deptofdefense/move.mil#387]
Please update the consumables section: Moving Guide > Entitlements/Guidelines > Special Item Information:

with the following information 

Only allowed for eligible locations.
If you are assigned to a permanent duty station  location listed ion the JTR, website at, http://www.defensetravel.dod.mil/Docs/AP-CG-01.pdf  you can ship up to 1,250 pounds of suitable consumable goods per a tour year assignment (i.e. 12-month tour - 1,250 lbs; 18-month tour - 1,875 lbs).
Consumable goods must be packed, marked and weight separately.
Contact your local Personal Property Office (PPPO) for more details

Below is a screenshot of the location to be updated

![consumables](https://user-images.githubusercontent.com/36198616/37741567-db24f4d8-2d2f-11e8-9e28-ab508e7f437c.PNG)

**Comment by jillesmith1** [comment]
No action required--closed.
