### ISSUE TITLE
Please update moving guide (Personal watercraft not primary reaidence)

### ISSUE THREAD

**Issue by robert078** [deptofdefense/move.mil#388]
Please update the boat or personal watercraft (Not primary residence) FOR OCONUS: Moving Guide > Entitlements/Guidelines > Special Item Information:

Please update to read as follows:

For larger boats, you will need to visit your Personal Property Office (PPPO) so that they can schedule a separate shipment with a commercial boat hauler. You will be responsible for excess cost - See above.

Below is a screenshot of the section to be changed

![boat or personal watercraft](https://user-images.githubusercontent.com/36198616/37742049-001b4c2c-2d32-11e8-985d-f30461eb7d63.PNG)

**Comment by jamesatheyDDS** [comment]
Perhaps instead of removing "a price" from this paragraph it should read "_and_ price".

**Comment by robert078** [comment]
No matter what its a separate shipment. When they arrange the shipment the will get the additional cost by going through the process.

**Comment by jillesmith1** [comment]
No action required--closed. Language and content is IAW Move.mil design principles.
