### ISSUE TITLE
Please update moving guide (Mobile Home)

### ISSUE THREAD

**Issue by robert078** [deptofdefense/move.mil#389]
In the picture with the mobile home delete just the word RV in the caption under the picture. 

Mobile Home (RVs, Tiny Houses, etc.)

Below is a screenshot of the area to be changed
![mobile home](https://user-images.githubusercontent.com/36198616/37742784-0c9daad2-2d35-11e8-84a9-e52e0e45f167.PNG)

**Comment by jamesatheyDDS** [comment]
@robert078 Why does "RV" need to be removed?

**Comment by robert078** [comment]
RVs are not authorized to be moved as a mobile home per the JTR

**Comment by jillesmith1** [comment]
Valid--for developer action. After clicking the **Mobile **Home** hyperlink on the subject page, please remove the letters "RV" from under the mobile home icon. 

NOTE:  RVs are considered POVs for the purposes of transportation per JTR Appendix A, definition of PRIVATELY OWNED VEHICLE (POV), paragraph B, page A-38 to A-39.

**Comment by pglevy** [comment]
We should change the icon as well since we're removing the RV text because they don't fall under this category but we're currently using a graphic that looks like an RV. @lfantano, are there source files available for these icons?

**Comment by ivonne-gov** [comment]
@jillesmith1, @pglevy with the fix, it looks like this:
<img width="130" alt="screen shot 2018-03-29 at 4 13 25 pm" src="https://user-images.githubusercontent.com/37001835/38111278-5c82510a-336c-11e8-8261-e95630f0fa47.png">

Should we remove the ", etc" as well? And just leave "Mobile Home (Tiny Houses)"

**Comment by jgarber623-gov** [comment]
Closed by #405.
