### ISSUE TITLE
Update Tutoral create a shipment slide 14

### ISSUE THREAD

**Issue by robert078** [deptofdefense/move.mil#392]
Tutorial > Create a Shipment

Under slide 14 (Pro Tips) Update  first bullet to read A POV is your Personally Privately Owned Vehicle. Please contact your local Transportation Office for any questions you may have regarding vehicles. 

Below is a screenshot of the location for the update

![create a shipment slide 14](https://user-images.githubusercontent.com/36198616/37774178-8fe24056-2dad-11e8-826f-633d1de291a0.PNG)

**Comment by jillesmith1** [comment]
No action required.
