### ISSUE TITLE
Update FAQs what is unaccompanied baggage

### ISSUE THREAD

**Issue by robert078** [deptofdefense/move.mil#393]
FAQS > Before You Move > What is Unaccompanied Baggage?

Please correct first paragraph to read:
This  is part of the member's weight allowance that is separated from other Household Goods and is shipped via an expedited mode because it's needed immediately or soon after arrival at the destination and prior to the arrival of Household Goods. This typically occurs with an OCONUS move.

Below is a screenshot of the location of the change 

![faqs before you move](https://user-images.githubusercontent.com/36198616/37774473-4a4d7474-2dae-11e8-9d59-effe106b283e.PNG)

**Comment by jamesatheyDDS** [comment]
@robert078 Can you elaborate on the reasoning behind this change? Is it important to not list specific shipping companies?

**Comment by robert078** [comment]
Unaccompanied baggage only uses military air...the company responsible for the shipment will be annotated on the bill of lading and that's who the customer will deal with fo track and or file a claim with.

**Comment by jillesmith1** [comment]
Valid.  @jamesatheyDDS  and @robert078  , Commercial air is also used to move UB shipments; however, removing "USPS, UPS, DHL, FedEx, etc." eliminates customer confusion that the government _is_ using these companies or methods to ship their UB when the shipments go via military air. (In other words, this is too much information to put out in the personal property/household goods/Move.mil atmosphere!)
