### ISSUE TITLE
Update FAQ After the move (What type of surveys)

### ISSUE THREAD

**Issue by robert078** [deptofdefense/move.mil#394]
FAQs > After the Move > What type of surveys can I be expected to fill out?

Please update paragraph to read:
At the end of the your move, you are required to  fill out the customer satisfaction survey. This provides the Personal Property offices with direct feedback on your moving company. Be honest and leave comments – if they were a great mover we want to make sure they get the chance to work with members and their families in the future. If they were not so great… we want to make sure they don’t receive future opportunities.

Below is a screenshot of the location to be updated
![faqs what survey](https://user-images.githubusercontent.com/36198616/37774658-d22a719e-2dae-11e8-9e84-de3235137058.PNG)

**Comment by jamesatheyDDS** [comment]
@robert078 Is it accurate to say that the most substantive change you are suggesting is to say that filling out the survey is required instead of highly recommended?

**Comment by robert078** [comment]
Correct. I changed it to reflect what I want it to read so as to eliminate confusion of which words where.

**Comment by jillesmith1** [comment]
VALID--for development action. Please change the first sentence to read, "At the end of the your move, you are required to fill out the customer satisfaction survey... "

**Comment by scottqueen-bixal** [comment]
@jillesmith1 can you confirm that the correct content for this update should read,

At the end of your move, you are required to fill out the customer satisfaction survey. This provides the Personal Property offices with direct feedback on your moving company. Be honest and leave comments – if they were a great mover we want to make sure they get the chance to work with members and their families in the future. If they were not so great… we want to make sure they don’t receive future opportunities

noticed an extra "the" in the original request.
