### ISSUE TITLE
Update Tools & Resources (PPM Estimator)

### ISSUE THREAD

**Issue by robert078** [deptofdefense/move.mil#395]
Tools & Resources > PPM Estimator:

Please update Notes bottom of page to read:
Note: This tool only provides an estimate of what you might receive if you decide to do a personally procured move. Your actual incentive will be calculated based off the rates available when you schedule your move in DPS. Rates vary based on transporter availability, the selected move date (Peak vs. Non-Peak Season), distance traveled, and the actual weight of the shipment. 

Below is a screenshot of the location to be updated. 
![ppm estimator](https://user-images.githubusercontent.com/36198616/37774858-579ff6b4-2daf-11e8-804c-42b5719c6cbb.PNG)

**Comment by jamesatheyDDS** [comment]
@robert078 The only difference I see between your text and the current text is an additional "the" before "selected move date." Is that what you're talking about?

**Comment by robert078** [comment]
Comment was changed to reflect the actual change. Daily is the word to delete and I kept it in there, sorry.

**Comment by robert078** [comment]
Rates are set during rate filing and if you eliminate daily it leaves will be calculated based off the rates available when you schedule your move. just reduces unnecessary wording.

**Comment by jillesmith1** [comment]
CONCUR--for developer action. Change second sentence text to read, "**Your actual incentive will be calculated using the current rates on the day you schedule your move in DPS.**"
