### ISSUE TITLE
Clarify difference between 75 day claim intent versus 9 month final submission of claim

### ISSUE THREAD

**Issue by schustdj** [deptofdefense/move.mil#400]
Thanks for submitting an issue! Below are a few things you can do to help us more quickly address the issue.

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [x] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior

It might help if the first paragraph in the article section of the "Loss & Damage Claims" page stated:

"If any of your household goods are lost or destroyed during the moving process, you are entitled to full replacement value of that item, assuming you **submit a loss/damage report or claim within 75 days following the date of delivery (Must submit final claim within 9 months of delivery date if only filing loss/damage report by 75 day mark).**

Note: _This is just a suggestion. Any other ideas on how to clarify immediately what needs to happen and by when?_

## Observed Behavior

First paragraph in the article section of the "Loss & Damage Claims" page states:

"If any of your household goods are lost or destroyed during the moving process, you are entitled to full replacement value of that item, assuming your claim is filed within the nine months following the date of delivery." 

Note: _The clarification of the difference between filing a loss/damage report and submitting a claim doesn't happen until the Loss/Damage Report Header and the "Important Dates With/Without Loss Damage Report" Tables in that section. I guess I am worried that service members will see 9 months first and not scroll any further down the page._

## Steps to Reproduce

To reproduce this issue…

1. https://www.move.mil/ 
2. then navigate to ->Moving Guide ->Loss & Damage Claims
3. Read the paragraph up at the top
4. Scroll down to see the section that clarifies, which is further down the page.

## Screenshots

![loss and damage screenshot](https://user-images.githubusercontent.com/35304127/38066764-0ee6b622-32cf-11e8-83d5-070297ad4db6.JPG)
_Attach relevant screenshots here._

**Comment by jillesmith1** [comment]
VALID--for developer action. Replace the first and second sentence text to read, "If any of your household goods are lost or destroyed during the moving process, you are entitled to full replacement value of that item, assuming you submit a loss or damage notification report within 75 days after your things are delivered to your new home. **All claims must be submitted in the Defense Personal Property System (DPS), which is the portal your move originally was scheduled in.**"  The remaining text is fine as it is written.
