### ISSUE TITLE
Determine deploy strategy

### ISSUE THREAD

**Issue by jgarber623-gov** [deptofdefense/move.mil#41]
☝️ Mostly what it says on the tin. This will require some investigation into the hosting environment and coordination with the responsible parties.

**Comment by Elliottdotgov** [comment]
Started convos with folks on the USTC hosting side. More to come.

**Comment by jgarber623-gov** [comment]
For our development purposes, as of last week we've got a successful deploy pipeline to DDS' AWS account.

**Comment by Elliottdotgov** [comment]
much of this is covered here: https://docs.google.com/document/d/1wQQNNr0qxbEu1frodnjkjE6wF1Wt9gywL3tW6xyPf7M/edit
the rest is covered in deploy instructions
