### ISSUE TITLE
PPM Estimator: All services now offer a 60% advance

### ISSUE THREAD

**Issue by jamesatheyDDS** [deptofdefense/move.mil#415]
The PPM Estimator currently asks for the branch of service so that it can show an advance of 50% for the Marines and 60% for everyone else.

According to MARADMIN 192/18,
> Marines may receive an Advance Operating Allowance (AOA) of up to 60% of the expected cost to move the estimated weight.

Assuming there is no other reason to ask for branch of service, simply remove that drop-down from the form, and use 60% to calculate the advance for all users.

**Comment by jillesmith1** [comment]
CONCUR--ain't it grand to have the same process across all Services?
