### ISSUE TITLE
Update PPPO Address and Phone Numbers and remove duplicate entry for the PPPO Ft Leavenworth, KS

### ISSUE THREAD

**Issue by humlah** [deptofdefense/move.mil#422]
Request received on 4/17 from Rita Newbell-Wright, Chief, Transportation Division, Ft Leavenworth, KS  Phone: 913-684-5630, email: rita.a.newbell-weight.civ@mail.mil.  Requesting address for the Ft Leavenworth, KS PPPO office be updated to show as follows:
549 Kearny Ave
Building 248
Fort Leavenworth, KS 66048.

## Checklist

It was discovered while verifying current data displayed on the move.mil website that this PPPO is showing twice.  After phone conversation with Ms Newbell-Wright she is requesting the record showing all boxes highlighted for services be the one to remove.  Then requesting the remaining one be updated to show the above new location, she is also requesting the Phone values be updated from (913)684-5656,5651,5655,5643 (voice) and 552-5656,5651,5655,5643(DSN) be changed to show only
(913)684-5656 (voice) and 552-5656 (DSN)

- [x ] described in detail below both the behavior I expected and the behavior I observed.
- [ x] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [ x] attached screenshots illustrating relevant behavior.

## Expected Behavior
Once Duplicate entry is removed, the PPPO Fort Leavenworth, KS should display as follows
Location:
549 Kearny Ave
Building 248
Fort Leavenworth, KS 66048
United States
Email: remains the same , no changes needed.
SERVICES:  
Walk-in Help         Computer Lab
 Appointments    QA Inspections
Phone:
(913)684-5656 (voice)
552-5656 (voice) (DSN)
_Summarize expected behavior._

## Observed Behavior

_Summarize observed behavior._

## Steps to Reproduce

To reproduce this issue…

1. _Describe step one._
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[PPPO Ft Leavenworth - Move.mil.docx](https://github.com/deptofdefense/move.mil/files/1939129/PPPO.Ft.Leavenworth.-.Move.mil.docx)

**Comment by jgarber623-gov** [comment]
Resolved by #429.
