### ISSUE TITLE
Update contact information PPSO Miami, FL

### ISSUE THREAD

**Issue by robert078** [deptofdefense/move.mil#423]
Lucia Larson from USCG Miami requested that contact information for PPSO Miami Beach be updated to reflect the following:

Telephone number: 305-216-8037
Email address: PPSOMIAMI@uscg.mil

Other telephone and email information should be deleted and replaced with the above. 

Below is the current information for PPSO Miami Beach for reference.
![ppso miami beach](https://user-images.githubusercontent.com/36198616/39266901-f0b85962-4890-11e8-9086-f307115399d7.PNG)

**Comment by jgarber623-gov** [comment]
Resolved by #429.
