### ISSUE TITLE
What to expect .. TDY

### ISSUE THREAD

**Issue by lfantano** [deptofdefense/move.mil#65]
Needs:

- [x] Page Template/Design
- [x] Content
- [ ] Implementation

Would love:

- Help collecting what to expect from TDY content... I have no idea.

**Comment by jde1984** [comment]
https://docs.google.com/a/dds.mil/document/d/1l3CPMTZZRncD_KD782bVseGjOsO7JtmPkBal23Dk0dU/edit?usp=sharing

Content.

**Comment by lfantano** [comment]
Design on Zeplin
https://app.zeplin.io/project/596e69460294feaa7dcfb194/screen/5a00b8323637f65c2145aae7
No graphics necessary...

**Comment by jde1984** [comment]
@lfantano @aileendds - under the weight table, can you guys add the following paragraph which will cover the allowance for civilian employees?
---
Civilian Employees, with authorization from the Approving Official on an extended TDY assignment, may ship up to 350 lbs.  This unaccompanied baggage is limited to additional clothing, personal effects, and equipment directly related to the mission, locality, or unusual conditions of the assignment. 
---

**Comment by aileendds** [comment]
merged! if there are any other content changes please create a new issue
