### ISSUE TITLE
What to expect ... Retirement/Separtee

### ISSUE THREAD

**Issue by lfantano** [deptofdefense/move.mil#66]
Needs: 

- [x] Page Template/Design
- [x] Content
- [ ] Implementation

**Comment by lfantano** [comment]
Design is up!
https://app.zeplin.io/project/596e69460294feaa7dcfb194/screen/5a01db1cf659129d1d5d4b1d

Necessary Graphics attached!
[ProTip.svg.zip](https://github.com/deptofdefense/move.mil/files/1450941/ProTip.svg.zip)

**Comment by aileendds** [comment]
@lfantano @jde1984 The content for Advance Payment for PPM and Short-Distance Move sections looks incomplete

**Comment by lfantano** [comment]
@aileendds We need to change the Marines advance payment info...

Marines: Marine Retirees and Separatees can recieve an advancement of up to 60% of the 95% PPM incentive payment. To receive your advancement, you must complete a [detailed weight inventory](url) and reach out to your [local Personal Property office (PPPO)](url) to arrange for a local quality assurance inspector to visit your residence to verify your estimated weight.

**Comment by aileendds** [comment]
Is the detailed weight inventory supposed to link to the self-inventory form when that's done?

**Comment by lfantano** [comment]
It should link to the weight calculator... maybe we need to change the text to "detailed weight calculation" to make that more clear.
