### ISSUE TITLE
Moving Tips Page

### ISSUE THREAD

**Issue by lfantano** [deptofdefense/move.mil#68]
Needs: 

- [x] Designs/Template
- [x] Content (Created, needs aggregated)
- [ ] Implementation

**Comment by jde1984** [comment]
[Lessons Learned  Tips.docx](https://github.com/deptofdefense/move.mil/files/1246244/Lessons.Learned.Tips.docx)

Content!

**Comment by lfantano** [comment]
Designs for "Prepping the Move" uploaded to Zeplin. Graphics below...

**Comment by Elliottdotgov** [comment]
@jamesatheyDDS @jgarber623-gov do y'all have what you need to get this up?

**Comment by jgarber623-gov** [comment]
@Elliottdotgov We should be good to get going on this one.

**Comment by Elliottdotgov** [comment]
woot!

**Comment by lfantano** [comment]
I think I might owe content for the third tab, no? My bad...
