### ISSUE TITLE
Weight Calculator Page

### ISSUE THREAD

**Issue by lfantano** [deptofdefense/move.mil#70]

**Comment by aileendds** [comment]
@lfantano -- I built this page using some basic UI components. Could you take a look at it and improve the design? 

The data is scraped from the DPS weight calculator.

<img width="1067" alt="screen shot 2017-10-11 at 5 19 35 pm" src="https://user-images.githubusercontent.com/29409348/31467616-96697e6e-aea8-11e7-9097-3676164eff4d.png">

<img width="1063" alt="screen shot 2017-10-11 at 5 19 53 pm" src="https://user-images.githubusercontent.com/29409348/31467625-9e4ab382-aea8-11e7-80f2-329a0f988939.png">

<img width="1135" alt="screen shot 2017-10-11 at 5 20 17 pm" src="https://user-images.githubusercontent.com/29409348/31467631-a2219eb2-aea8-11e7-9105-200efd656dfb.png">

**Comment by aileendds** [comment]
Closing out v1, v2 tracked here: https://github.com/deptofdefense/TRANSCOM/issues/28
