### ISSUE TITLE
Tutorial: Cancel a Shipment

### ISSUE THREAD

**Issue by LillyMadigan** [deptofdefense/move.mil#82]
New tutorial content below, with images saved in the folder:

Step & Content

Step | Content | Links
1 | Login to **ETA** and open the DPS homepage. Select “Self Counsel” to locate the shipment you want to cancel. Shipments are listed under the Orders from which they were created. Since you can have more than one shipment per Order, it's important to carefully select only the shipment you want to cancel. 

Already assigned a Transportation Service Provider (TSP)? You must **contact your local Counseling Office**, and request a cancellation in writing. 

PRO TIP: Need help getting to this page? Check out the Returning User Login tutorial. 
-------
Links:
ETA: https://eta.sddc.army.mil/ETASSOPortal/Default.aspxLink to PPPO Map. 
Link to Returning User Login tutorial

2 | Locate the Orders of your shipment and click the "Action" icon next to the shipment you want to cancel. 

3 | Choose which shipment you'd like to cancel from the menu on the left to open the details of the shipment. 

4 | Click the "Cancel" icon. 

5 | Confirm this is the shipment you want to cancel, and click "OK".

**Comment by jgarber623-gov** [comment]
Superseded by #182.

**Comment by LillyMadigan** [comment]
Content
https://docs.google.com/a/dds.mil/document/d/1a3hJFjt8b00dWkammOVSgjcoVuAFrzWVYQMF4UaQ09Y/edit?usp=sharing

Images
https://drive.google.com/drive/folders/1VYMDqpcwJC_UYnf37aQvSq7pKcci3PFF?usp=sharing

Design in Zeplin
