### ISSUE TITLE
Tutorial: Dual Military (Mil-to-Mil) move

### ISSUE THREAD

**Issue by LillyMadigan** [deptofdefense/move.mil#83]
Pics are finished and up on transom google docs https://drive.google.com/open?id=0B3pZxjYJ-QZwWTBTbUtNckxzaDQ

Step | Content
1 | A Dual Move, also known as Mil-to-Mil, is when your spouse or significant other is also a service member or government civilian and you both have Orders to PCS. Check out the FAQ for details about weight allowances, and examples of Mil-to-Mil move scenarios. First, log into ETA, and choose DPS from your list of approved applications. PRO TIP: Turn off your pop-up blocker, otherwise the DPS window won't be able to open.
2 | On the DPS homepage, select “Self Counsel” to begin your application.
3 | Scroll down to find the Customer Information page. During this process, if you find a blank screen, don't worry - just scroll down to find the information you're looking for.
4 | You'll find an overview of the Counseling Process, but to get to the first step, click on the Customer Information button in the Counseling Menu on the left side of the page. PRO TIP: If you've moved before, DPS will save your information so that it's pre-poulated here, and you won't have to fill it out again.
5 | Fill out your Customer Information and Permanent Contact Address. The "Permanent Contact Address" is the place where you're living right now. Addresses are saved in DPS so you don't have to fill it out each time you schedule a move. PRO TIP: You can check your progress in the Counseling Menu on the left side of the page. CONUS stands for Continental United StatesOCONUS stands for Outside Continental United States
6 | Enter a Point of Contact who will be traveling or moving with you. This person will have access to shipment status and information. PRO TIP: A Letter of Authorization allows you to give another person permission to act on your behalf. Only the service member who has official orders can write this letter of authorization.
7 | Here, indicate your rank, and whether or not you're allowed PBP&E. This information allows DPS to calculate your shipment weight allowance, if it wasn't part of your orders.PRO TIP: PBP&E is the "pro gear" or professional equipement you might need to ship - there's an extra separate allowance for you, and your spouse. A "Hard Copy" of your orders means that you recieved orders your can upload into DPS as a pdf, Word Doc, Text File, etc.
8 | Next, enter the address you are leaving, and your new address.
9 | Specify your authorized Order Type, and upload a copy of your Order document. Create your shipment based on your orders by first selecting the type. Upload both sets of Orders for you and your spouse. PRO TIP: Can't find your type? Check out the category "Various" to see miscellaneous move types.
10 | Next, enter your new Duty Station and indicate whether or not you're moving with dependents (including a spouse).
11 | Finally, in the Additional Information section, you'll specify if you need to ship a POV, motorcycle, etc. PRO TIP: A POV is your Personally Owned Vehicle, and in this context, a "Mobile Home" is an RV.
12 | The Order Summary allows you to review and certify the information you entered is accurate. PRO TIP: Your weight allowance is listed here in the second paragraph!
13 | Now that you've entered your Orders information, you must "Create New Shipment" specific for those orders. Select the type of shipment you want to create, like "HHG", and specify whether or not it will be a Personally Procured Move (PPM). PRO TIP: You can create more than one type of shipment per Orders. For example, you can schedule an HHG shipment for the majority of your belongings that the government will move for you, and an additional PPM shipment for the ones you'll move by yourself.
14 | Then you'll get some helpful information about the type of move you selected.
15 | Set your desired moving dates, and enter the pick-up and drop-off addresses.
16 | Next, define you shipment weight, and let us know if you have special items like a jacuzzi or piano. There's also a separate section for firearms on the next page. Enter your spouse's information here in the "Additional Information" section.-Name of Spouse or Significant Other-Rank-Branch of Service-Orders Number-Total Estimate Weight of the Shipment
17 | Here, indicate if you are shipping any firearms.
18 | If you have a preference, here's where you can let us know your favorite (or least favorite) Transportation Service Provider (TSP).
19 | Now it's time to go over moving day responsibilities for you and your TSP (moving company).
20 | A summary of your shipment is then provided for your review and acknowledgement.
21 | Here you'll choose a local Personal Property Office for counseling, who you will contact after submitting your shipment on DPS. They'll need the signed DD1299 and DD1797 forms generated on the next page.
22 | On this Submit Page, review, print, and sign your forms DD1299 and DD1797. Upload them back into DPS on this screen and press submit.

**Comment by LillyMadigan** [comment]
Pics are up on https://drive.google.com/open?id=0B3pZxjYJ-QZwWTBTbUtNckxzaDQ

**Comment by jgarber623-gov** [comment]
Superseded by #182.

**Comment by LillyMadigan** [comment]
Content: https://docs.google.com/a/dds.mil/document/d/1lgYLvLoSV0OpEYcR5zxU1Htw71QiNLaE6iNfV33O0Ms/edit?usp=sharing

Images: 
https://drive.google.com/drive/folders/1jyjNGbD9hFTbbwrpp6W20rDKhY38StQr?usp=sharing

**Comment by LillyMadigan** [comment]
Final Content
https://docs.google.com/a/dds.mil/document/d/1lgYLvLoSV0OpEYcR5zxU1Htw71QiNLaE6iNfV33O0Ms/edit?usp=sharing

Final Images https://drive.google.com/open?id=1kRh20tLDWPrBhznLeURqQ6TDptogPfkZ

Design is up in Zeplin
