### ISSUE TITLE
Locator Maps: Military ZIP codes

### ISSUE THREAD

**Issue by jamesatheyDDS** [deptofdefense/move.mil#86]
The ZIP code search on the Locator Maps page utilizes data from the Census, specifically the zip code tabulation areas. This list does not appear to include any military bases, domestic or foreign.

Either locate a source for the military ZIP code geolocations, or manually look up the FPO / APO zip codes, get the geolocation of the corresponding military installations, and add them to the data we already have.

**Comment by jgarber623-gov** [comment]
Posting a couple links here that might be useful:

- http://federalgovernmentzipcodes.us
- https://heuristically.wordpress.com/2010/11/11/zip-code-list-us-military-installations/

**Comment by jamesatheyDDS** [comment]
If we have search by military installation (see #89), then adding the military FPO / APO zip codes is probably unnecessary.

**Comment by jgarber623-gov** [comment]
Closing based on @jamesatheyDDS' comment and @Elliottdotgov's confirmation.
