### ISSUE TITLE
Add DFAS contact information

### ISSUE THREAD

**Issue by jgarber623-gov** [deptofdefense/move.mil#91]
Coming out of last week's Design Sprint, I have a Post-It note on my laptop:

> Get DFAS phone number to add to beta.move.mil

☝️ I poked around [dfas.mil](https://www.dfas.mil) and found [this askDFAS page](https://corpweb1.dfas.mil/askDFAS/welcome.action) that has a phone number listed at the top: `1-888-332-7411`.

There's also [a DFAS Facebook page](https://www.facebook.com/DefenseFinanceandAccountingService) with nearly 100,000 "likes."

It's not clear from the Post-It note where we might want to include this phone number (or any other DFAS-related information). @Elliottdotgov, can you clarify?

**Comment by Elliottdotgov** [comment]
yeah, i think we add their `askDFAS` page link and the phone number...maybe on the `Customer Service` page? cc @lfantano

**Comment by Elliottdotgov** [comment]
let's just add this if we get a request down the road...
