### ISSUE TITLE
Moving Tips: At Your Destination

### ISSUE THREAD

**Issue by jamesatheyDDS** [deptofdefense/move.mil#92]
We need content for the "At Your Destination" tab on the Moving Tips page.

**Comment by jde1984** [comment]
Content was loaded in the larger Moving Tips issue. 

https://github.com/deptofdefense/move.mil/issues/68

**Comment by lfantano** [comment]
Move Tips has been reformatted based on user feedback and to fit the new template. It should be refactored for launch. 

Designs:
https://zpl.io/b6JjYzj

Content (Tip Expanded Accordians)
https://docs.google.com/a/dds.mil/document/d/1AyxGyn0MK2S40mR-j32HaFYk8efHYcscCuvnE8HPu_Q/edit?usp=sharing

Assets:
[MoveTips.zip](https://github.com/deptofdefense/move.mil/files/1492456/MoveTips.zip)
